defaults:
  - /env/mettagrid/navigation/navigation_sequence/defaults@
  - _self_

game:
  num_agents: 1  #how many agents are in the map x2
  max_steps: 500
  agent:
    rewards:
      heart: 1

  map_builder:

    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 1
    room:
      _target_: mettagrid.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/navigation/navigation_sequence/wanderout.map"

  objects:
    altar:
      cooldown: 255
    mine:

  objects:
    altar:
      hp: 30
      input_battery: 1
      output_heart: 1
      max_output: 1
      conversion_ticks: 1
      cooldown: ${sampling:1, 20, 10}
      initial_items: 0

    mine.red:
      hp: 30
      output_ore.red: 1
      color: 0
      max_output: 1
      conversion_ticks: 1
      cooldown: ${sampling:0, 100, 50}
      initial_items: 1

    generator.red:
      hp: 30
      input_ore.red: 1
      output_battery: 1
      color: 0
      max_output: 1
      conversion_ticks: 1
      cooldown: ${sampling:0, 50, 25}
      initial_items: 1
