defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 48
  agent:
    max_inventory: 5
  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
        width: ${sampling:50,100,60}
        height: ${sampling:50,100,60}
        border_width: ${sampling:1,6,3}
        agents: 12
        style: sparse-altars-dense-objects # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
        team: team_1
      - _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
        width: ${sampling:50,100,60}
        height: ${sampling:50,100,60}
        border_width: ${sampling:1,6,3}
        agents: 12
        style: sparse-altars-dense-objects # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
        team: team_2
      - _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
        width: ${sampling:50,100,60}
        height: ${sampling:50,100,60}
        border_width: ${sampling:1,6,3}
        agents: 12
        style: sparse-altars-dense-objects # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
        team: team_3
      - _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
        width: ${sampling:50,100,60}
        height: ${sampling:50,100,60}
        border_width: ${sampling:1,6,3}
        agents: 12
        style: sparse-altars-dense-objects # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
        team: team_4

  reward_sharing:
    groups:
      team_1:
        team_1: 0.2
      team_2:
        team_2: 0.4
      team_3:
        team_3: 0.6
      team_4:
        team_4: 0.8
