
defaults:
  - mettagrid

sampling: 1

game:
  num_agents: 24

  agent:
    rewards:
      action_failure_penalty: 0
      heart: 5

  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,25,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,12}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,25,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,25,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,16,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine: 1
          generator: 1
          altar: 1
          wall: ${uniform:5,25,20}
  objects:
    mine:
      hp: 30
      cooldown: 1
    generator:
      hp: 30
      cooldown: 5
    altar:
      hp: 30
      cooldown: 10

  actions:
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false
