
defaults:
  - mettagrid

sampling: 1

game:
  num_agents: 24

  agent:
    rewards:
      action_failure_penalty: 0
      ore: 0
      battery: 1

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${..num_agents}
    border_width: 6

    room:
      _target_: mettagrid.config.room.random.Random
      width: ${uniform:10,50,25}
      height: ${uniform:10,50,25}
      border_width: 1

      agents: 1

      objects:
        mine: 1
        generator: 1
        wall: ${uniform:5,25,20}
  objects:
    mine:
      hp: 30
      cooldown: 1
    generator:
      hp: 30
      cooldown: 10

  actions:
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false
