defaults:
  - mettagrid

game:
  num_agents: 5

  map_builder:
    _target_: deps.mettagrid.mettagrid.config.maze_builder.RepeatRoom
    num_rooms: 5
    template:
      _target_: deps.mettagrid.mettagrid.config.maze_builder.MazeRoom
      width: 40
      height: 40
      start_pos: [1, 1]
      end_pos: [39, 39]
      branching: 0.7

  objects:
    altar:
      cooldown: 255
    agent:
      initial_energy: 255

