_target_: metta.rl.pufferlib.trainer.PufferTrainer

defaults:
  - trainer
  - _self_

resume: true
use_e3b: false

total_timesteps: 50_000_000_000

clip_coef: 0.17341499774391853
ent_coef: 0.0021
gae_lambda: 0.916
gamma: 0.977

# optimizer:
#   type: muon
#   beta1: 0.943
#   beta2: 0.9997
#   eps: 1.82e-13
#   learning_rate: 0.000238167

optimizer:
  type: muon
  beta1: 0.862440463915262
  beta2: 0.9995722874745067
  eps: 9.852709528951554e-13
  learning_rate: 0.0004573146765703167

prio_alpha: 0.8264083959224604
prio_beta0: 0.09999999999999998

lr_scheduler:
  enabled: false

max_grad_norm: 1.4335801872034548
max_minibatch_size: 32768

vf_clip_coef: 0.1
vf_coef: 0.44
l2_reg_loss_coef: 0
l2_init_loss_coef: 0

norm_adv: true
clip_vloss: true
target_kl: null

zero_copy: true
require_contiguous_env_ids: false
verbose: true

batch_size: 524288
# minibatch_size: 32768
minibatch_size: 16384
bptt_horizon: auto
update_epochs: 1

cpu_offload: false
compile: false
# compile_fullgraph: true
compile_mode: reduce-overhead
profiler_interval_epochs: 10000

forward_pass_minibatch_target_size: 2048
async_factor: 2

stats:
  overview:
    episode/reward.mean: episode_reward
  step: train/agent_step

kickstart:
  teacher_uri: null
  action_loss_coef: 1
  value_loss_coef: 1
  kickstart_steps: 50_000_000
  additional_teachers:
    # - teacher_uri: wandb://run/mettabox_cogeval_defaults_lowent_initialized0005:v100
    #   action_loss_coef: 1
    #   value_loss_coef: 1
    #  - teacher_uri: wandb://run/mettabox_cogeval_defaults_lowent_initialized0005:v95
    #    action_loss_coef: 1
    #    value_loss_coef: 1
