num_workers: ???

env: /env/mettagrid-base/simple
env_overrides: {}

initial_policy:
  uri: wandb://run/b.alex.can_simple_2.12 #wandb://run/alex.local.290 
  type: latest
  range: 1
  metric: epoch
  filters: {}

checkpoint_dir: ${run_dir}/checkpoints

glicko_scores_path: ${run_dir}/eval/glicko2

evaluate_interval: 300
checkpoint_interval: 60
wandb_checkpoint_interval: 100
replay_interval: ${trainer.evaluate_interval}

# Average reward settings
average_reward: false # Set to true to use average reward optimization
average_reward_alpha: 0.01 # Smoothing factor for 100k step average (ln(2)/100000)
