num_workers: ???

env: /env/mettagrid/simple
env_overrides: {}

initial_policy:
  uri: null
  type: top
  range: 1
  metric: epoch
  filters: {}

checkpoint_dir: ${run_dir}/checkpoints

glicko_scores_path: ${run_dir}/eval/glicko2

evaluate_interval: 300
checkpoint_interval: 60
wandb_checkpoint_interval: 300

trace_interval: 0

