_target_: rl.eval.eval_stats_analyzer.EvalStatsAnalyzer

artifact_name: null
version: null

file_path: null

table_name: eval_data

analysis:

  filters: null #global filters

  metric_patterns: null

  per_episode_metrics:
    - metric: "agent.action.use.altar"

  metrics:
    - metric: "agent.action.use.altar"

  statistical_tests:
    - type: mann_whitney
      metrics:
        - "agent.action.use.altar"
      mode: sum
      scores_path: "scores/altar_mann_whitney_scores.json"

    - type: elo
      metrics:
        - "agent.action.use.altar"
      mode: sum
      scores_path: "scores/altar_elo_scores.json"

    - type: glicko2
      metrics:
        - "agent.action.use.altar"
      scores_path: "scores/altar_glicko_scores.json"

  queries: null
