_target_: rl.eval.eval_stats_analyzer.EvalStatsAnalyzer

db_uri: ???

analysis:

  filters: null #global filters

  metric_patterns: null

  metrics:
    - metric: "agent.action.use.altar"

  queries: null
