_target_: rl.eval.eval_stats_analyzer.EvalStatsAnalyzer

db_uri: ???

analysis:

  filters: null #global filters

  metric_patterns: null

  per_episode_metrics:
    - metric: "agent.action.use.altar"

  metrics:
    - metric: "agent.action.use.altar"

  statistical_tests:

    - type: elo
      metrics:
        - "agent.action.use.altar"
      scores_path: "scores/altar_elo_scores.json"

    - type: glicko2
      metrics:
        - "agent.action.use.altar"
      scores_path: "scores/altar_glicko_scores.json"

  queries: null
