policy_uri: ${..policy_uri}
eval_db_uri: ${..eval_db_uri}

view_type: all
output_path: /tmp/dashboard.html
metric: group_rewards.team_1

analysis:
  metric_patterns: null

  metrics:
    - metric: group_rewards.team_1

  queries: null

  baseline_policies: null

  log_all: true
