_target_: rl.eval.eval_stats_analyzer.EvalStatsAnalyzer

policy_uri: ???

analysis:

  metric_patterns: null

  metrics:
    - metric: episode_reward
    - metric: ore.blue.get
    - metric: ore.red.get
    - metric: ore.green.get

  filters:
    policy_name:
      - ${policy_uri}


  queries: null

  baseline_policies: null

  log_all: true
