_target_: rl.eval.eval_stats_analyzer.EvalStatsAnalyzer

policy_uri: ???

analysis:

  metric_patterns: null

  metrics:
    - metric: episode_reward

  filters:
    policy_name:
      - ${policy_uri}



  # metrics:
  #   - metric: ore.blue.get
  #   - metric: ore.red.get
  #   - metric: ore.green.get

  queries: null

  baseline_policies: null

  log_all: true
