_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 50
                - 55
                - 105
            "2":
                - 50
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
duration_seconds:
    value: 60
env_config:
    value: benchmark
log_interval_seconds:
    value: 10
reset_interval:
    value: 1000
run_id:
    value: 1
