defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
<<<<<<< HEAD
  num_agents: 1
=======
  num_agents: 20
>>>>>>> 5fbdb29a5566bf93b5af83136ba052c1ded7cd98
  max_steps: 100

  agent:
    rewards:
      heart: 0.333

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 1
    border_width: 1

    room:
      _target_: mettagrid.config.room.mean_distance.MeanDistance
      width: 25
      height: 25
      mean_distance: 15
      border_width: 3

      agents: 1

      objects:
        altar: 3

  objects:
    altar:
      cooldown: 255
