defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

game:
  actions:
    attack:
      enabled: false
    put_items:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false
