defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
<<<<<<< HEAD
  num_agents: 1  #how many agents are in the map x2
=======
  num_agents: 20  #how many agents are in the map x2
>>>>>>> 5fbdb29a5566bf93b5af83136ba052c1ded7cd98
  max_steps: 150
  agent:
    rewards:
      heart: 0.333
  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 1
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/navigation/radial_mini.map"

  objects:
    altar:
      cooldown: 255
