defaults:
  - /env/mettagrid/navigation_sequence/defaults@
  - _self_

game:
  max_steps: 400
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 1
    room:
      _target_: mettagrid.room.ascii.Ascii
      border_width: 5
      uri: "configs/env/mettagrid/maps/navigation_sequence/cylinder_easy.map"
