defaults:
  - /env/mettagrid/mettagrid@
  - _self_

agents: 1

game:

  num_agents: 1
  max_steps: 700

  agent:
    max_inventory: 100
    freeze_duration: 0
    hp: 10
    mortal: False

  objects:
    altar:
      input_battery: 1
      output_heart: 1
      max_output: 1
      conversion_ticks: 1
      cooldown: 255
      initial_items: 0

    mine.red:
      hp: 30
      output_ore.red: 1
      color: 0
      max_output: 1
      conversion_ticks: 1
      cooldown: 255
      initial_items: 1

    generator.red:
      hp: 30
      input_ore.red: 1
      output_battery: 1
      color: 0
      max_output: 1
      conversion_ticks: 1
      cooldown: 255
      initial_items: 0