defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 14
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 1
    border_width: 0

    room:
      _target_: mettagrid.room.multi_agent.boxshare.BoxShare
      width: ${sampling:30,50,40}
      height: ${sampling:30,50,40}
      border_width: 0
      agents: 14
      objects:
        altar: 7
        mine: 7
        generator: 8
  objects:
    altar:
      cooldown: 255
      input_battery: 1
      output_heart: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
    mine:
      cooldown: 255
      output_ore: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 1
    generator:
      cooldown: 255
      input_ore: 1
      output_battery: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
