defaults:
  - /env/mettagrid/mettagrid@
  - _self_

# Randomly choose density if not overridden
# density: ${choose:sparse,medium,dense}

sampling: 1

game:
  num_agents: 20
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 1
    border_width: 0

    room:
      _target_: mettagrid.room.multi_agent.boxy.Boxy
      width: ${sampling:60,100,80}
      height: ${sampling:60,100,80}
      border_width: 0
      agents: 20
      objects:
        altar: ${sampling:10,14,12}
        mine: ${sampling:30,60,45}
        generator: ${sampling:30,60,45}

  objects:
    altar:
      cooldown: 255
      input_battery: 1
      output_heart: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
    mine:
      cooldown: 255
      output_ore: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 1
    generator:
      cooldown: 255
      input_ore: 1
      output_battery: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
