defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 96
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 1
    border_width: 6

    room:
      _target_: mettagrid.room.multi_agent.manhatten.Manhatten
      width: ${sampling:150,240,180}
      height: ${sampling:150,240,180}
      border_width: 2
      agents: 96
      corridor_spacing: ${sampling:15,40,25}
      alcove_prob: ${sampling:0.05,0.3,0.15}
      heart_prob: ${sampling:0.05,0.15,0.1}
      objects:
        altar: 24
        mine: 24
        generator: 24
  objects:
    altar:
      cooldown: 5
      input_battery: 1
      output_heart: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
    mine:
      cooldown: 5
      output_ore: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 1
    generator:
      cooldown: 5
      input_ore: 1
      output_battery: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
