num_envs: 1024
num_episodes: 1024
max_time_s: 60
policy_agents_pct: 0.5

policy:
  uri: null
  type: top
  range: 1
  metric: epoch
  filters: {}

baselines:
  elo_scores_path: null
  glicko_scores_path: null
  uri: null
  type: top
  range: 5
  metric: epoch
  filters: {}


