# eval:
#   fps: 8
#   max_steps: 1000
#   video_path: ${framework.train_dir}/${experiment}/replay.mp4
#   gif_path: ${framework.train_dir}/${experiment}/replay.gif

_target_: rl.pufferlib.evaluator.PufferEvaluator

defaults:
  - evaluator

