# eval:
#   fps: 8
#   max_steps: 1000
#   video_path: ${framework.train_dir}/${experiment}/replay.mp4
#   gif_path: ${framework.train_dir}/${experiment}/replay.gif

_target_: rl.pufferlib.evaluator.PufferEvaluator

num_envs: 1024
num_episodes: 1024
max_time_s: 60
policy_agents_pct: 0.5

policy_uri: ${data_dir}/${run}}
baseline_uris: []
max_baselines: 5
