# Config: Dense Obstacles & Sparse Altars
defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 4
  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
      width: ${sampling:50,100,60}
      height: ${sampling:50,100,60}
      border_width: ${sampling:1,6,3}
      agents: 1
      style: ${choose:"sparse-altars-dense-objects","all-sparse","balanced"}

  objects:
    altar:
      cooldown: 10
      input_battery: 1
      output_heart: 1
      max_output: 5
      conversion_ticks: 1
      initial_items: 0
    generator:
      initial_items: 5
      cooldown: 50
      conversion_ticks: 1
  
  agent:
    max_inventory: 10