_target_: rl.pufferlib.eval.Eval

policy_uri: ???
npc_policy_uri: null
policy_agents_pct: 1.0

device: ${device}
vectorization: ${vectorization}

num_envs: 128
num_episodes: 128
max_time_s: 60

log_eval_artifact: true
eval_artifact_name: eval_db
