_target_: rl.pufferlib.eval.EvalSuite

defaults:
  - eval

env: null #the env is set in evals:

evals:
  simple:
    env: env/mettagrid/colored_mines_meta_simplified_eval_two_colours
    policy_agents_pct: 1.0

  school:
    env: env/mettagrid/colored_mines_simplified_eval_three_colours
    policy_agents_pct: 1.0
