_target_: rl.pufferlib.eval.EvalSuite

defaults:
  - eval

env: null #the env is set in evals:

evals:
  simple:
    env: env/mettagrid/simple
    policy_agents_pct: 1.0
<<<<<<< HEAD

selector_type: latest
=======
>>>>>>> 603cb02abb8a6a469038f034ea8a205014c379f2
