_target_: metta.sim.simulation.SimulationSuite

defaults:
  - eval
  - _self_

env: null #the env is set in evals:

evals:
  simple_solo: #this will be in the title of the wandb eval plot
    env: env/mettagrid-base/simple
    policy_agents_pct: 0
