_target_: metta.sim.simulation.SimulationSuite

defaults:
  - eval
  - _self_

env: null #the env is set in evals:

evals:
  simple_npc_b.daveey.t.8.rdr9.3:
    env: env/mettagrid-base/simple
    policy_agents_pct: 0.5
    npc_policy_uri: wandb://run/b.daveey.t.8.rdr9.3
