defaults:
  - mettagrid

game:
  num_agents: 8

  map_builder:
    _target_: mettagrid.config.room.room_list.RoomList
    rooms:
      - _target_: mettagrid.config.room.cognitive_evals.combat_room_within_room.RoomWithinRoom
        width: 30
        height: 30
        inner_size_min: 10
        inner_size_max: 18
        inner_room_gap_min: 2
        inner_room_gap_max: 6
        # Specify teams and number of agents per team:
        agents: {"team_1": 4, "team_2": 4}
    layout: "grid"
    border_width: 1
    border_object: "wall"

  objects:
    altar:
      hp: 30
      cooldown: 1

    mine:
      hp: 30
      cooldown: 1

    generator:
      hp: 30
      cooldown: 1

  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false