defaults:
  - mettagrid

game:
  num_agents: 2

  map_builder:
    _target_: mettagrid.config.room.room_list.RoomList
    rooms:
      - _target_: mettagrid.config.room.cognitive_evals.combat_friend_or_foe.CombatFriendOrFoe
        width: 40
        height: 10
        # Specify teams and number of agents per side:
        agents: {"team_1": 1, "team_2": 1}
    layout: "grid"
    border_width: 1
    border_object: "wall"

  objects:
    altar:
      hp: 30
      cooldown: 1
    mine:
      hp: 30
      cooldown: 1
    generator:
      hp: 30
      cooldown: 1

  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false