defaults:
  - mettagrid

game:
  num_agents: 6    # Updated for 9 room types with 2 rooms each

  map_builder:
    _target_: mettagrid.config.room.room_scene.RoomScene
    border_width: 0

    layout: [
      [ "cylinder", "radial"],
      [  "corridor", "barriermaze"],
      ["room_within_room", "explore_exploit"],
      [  "labyrinth", "cylinder"],
    ]
    # List of room configurations
    rooms:
      cylinder:
        _target_: mettagrid.config.room.cognitive_evals.cylinder.Cylinder
        width: ${uniform:8,12,21}
        height: ${uniform:8,12,21}
        agents: 0
        border_width: 0
        cylinder_params:
          length: ${uniform:3,4,5}
          horizontal: ${choose:true,false}
          both_ends: ${choose:true,false}
      radial:
        _target_: mettagrid.config.room.cognitive_evals.radial_maze.RadialMaze
        width: ${uniform:8,12,21}
        height: ${uniform:8,12,21}
        border_width: 0
        radial_params:
          num_arms: ${uniform:4,8,6}
          arm_length: ${uniform:7,10,7}
          center_radius: ${uniform:2,4,3}
      explore_exploit:
        _target_: mettagrid.config.room.cognitive_evals.explore_exploit.ExploreExploit
        width: ${uniform:8,12,21}
        height: ${uniform:8,12,21}
        agents: 0
        border_width: 0
        explore_exploit_params:
          obstruction_gap_prob: ${uniform:0.3,0.6,0.2}
          sparse_min_distance: ${uniform:6,10,8}
      labyrinth:
        _target_: mettagrid.config.room.cognitive_evals.labyrinth.LabyrinthMaze
        width: ${uniform:25,35,21}
        agents: 0
        height: ${uniform:25,35,21}
        corridor_width: ${uniform:1,4,3}
        border_width: 0
      corridor:
        _target_: mettagrid.config.room.cognitive_evals.corridor_maze.CorridorMaze
        width: ${uniform:18,24,21}
        height: ${uniform:18,24,21}
        corridor_width: ${uniform:2,3,2}
        agents: 0
        arm_length: ${uniform:8,8,5}
        num_generators: ${uniform:1,3,2}
        num_convertors: ${uniform:2,4,3}
        num_heart_altars: ${uniform:2,4,3}
        rotate: ${choose:true,false}
        border_width: 0
      barriermaze:
        _target_: mettagrid.config.room.cognitive_evals.barriermaze.BarrierMaze
        width: ${uniform:15,25,21}
        height: ${uniform:15,25,21}
        barrier_width: ${uniform:1,3,2}
        agents: 0
        border_width: 0
        num_barriers: ${uniform:3,5,3}
        barrier_placement_mode: ${choose:"same","alternating","doorways"}
        barrier_orientation: ${choose:"vertical","horizontal"}
      room_within_room:
        _target_: mettagrid.config.room.cognitive_evals.room_within_room.RoomWithinRoom
        width: ${uniform:25,35,30}
        height: ${uniform:25,35,30}
        agents: 0
        border_width: 0
        inner_size_min: ${uniform:8,12,10}
        inner_size_max: ${uniform:15,20,18}
        inner_room_gap_min: 2
        inner_room_gap_max: ${uniform:4,8,6}
      maze:
        _target_: mettagrid.config.room.maze.MazeKruskal
        width: ${uniform:10,35,20}
        height: ${uniform:10,35,20}
        border_width: 0
        start_pos: [1, 0]
        end_pos:
        - ${sub:${..width},2}
        - ${sub:${..height},2}
        branching: ${uniform:0.1,0.8,0.7}

  objects:
    altar:
      hp: 30
      cooldown: 1

    mine:
      hp: 30
      cooldown: 1

    generator:
      hp: 30
      cooldown: 1

    armory:
      hp: 30
      cooldown: 1

    lasery:
      hp: 30
      cooldown: 1

    lab:
      hp: 30
      cooldown: 1

    factory:
      hp: 30
      cooldown: 1

    temple:
      hp: 30
      cooldown: 1

    wall:
      hp: ${uniform:1, 20, 10}

  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false
