defaults:
  - mettagrid

env:
  track_last_action: false

agent:
  observation_encoder:
    track_last_action: ${env.track_last_action}
sampling: 1

game:
  num_agents: 4
  max_steps: 250
  map_builder:
    _target_: mettagrid.config.room.room_list.RoomList
    rooms:
      - _target_: mettagrid.config.room.cognitive_evals.labyrinth.LabyrinthMaze
        width: ${uniform:20,25,21}
        height: ${uniform:20,25,21}
        corridor_width: ${uniform:1,4,3}
      - _target_: mettagrid.config.room.cognitive_evals.labyrinth.LabyrinthMaze
        width: ${uniform:20,25,21}
        height: ${uniform:20,25,21}
        corridor_width: ${uniform:1,4,3}
      - _target_: mettagrid.config.room.cognitive_evals.labyrinth.LabyrinthMaze
        width: ${uniform:20,25,21}
        height: ${uniform:20,25,21}
        corridor_width: ${uniform:1,4,3}
      - _target_: mettagrid.config.room.cognitive_evals.labyrinth.LabyrinthMaze
        width: ${uniform:20,25,21}
        height: ${uniform:20,25,21}
        corridor_width: ${uniform:1,4,3}

  objects:
    altar:
      hp: 30
      cooldown: 1

    mine:
      hp: 30
      cooldown: 1

    generator:
      hp: 30
      cooldown: 1

    armory:
      hp: 30
      cooldown: 1

    lasery:
      hp: 30
      cooldown: 1

    lab:
      hp: 30
      cooldown: 1

    factory:
      hp: 30
      cooldown: 1

    temple:
      hp: 30
      cooldown: 1

    wall:
      hp: ${uniform:1, 20, 10}