_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 50
                - 55
                - 105
            "2":
                - 50
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": darwin-arm64
env_config:
    value: benchmark
log_interval_steps:
    value: 1000
simulation_type:
    value: with_resets
steps_per_reset_cycle:
    value: 1000
total_steps:
    value: 10000
