
_target_: mettagrid.curriculum.curriculum.MultiEnvCurriculum

tasks:
  /env/mettagrid/simple: 0.5
  /env/mettagrid/teams: 0.25
  /env/mettagrid/bases: 0.25

env_overrides:
  game:
    num_agents: 24
    max_steps: 10

