_target_: metta.env.mettagrid_env_set.MettaGridEnvSet

num_agents: 10
sampling: 1

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/object_use/training/sequence_dr1
  - /env/mettagrid/object_use/training/sequence_dr2
  - /env/mettagrid/object_use/training/sequence_dr3
