defaults:
  - /env/mettagrid/in_context_learning/training/defaults@
  - _self_


game:
  map_builder:
    room:
      objects:
        mine.green: ${sampling:1, 5, 3}
        mine.red: ${sampling:1, 5, 3}
        mine.blue: ${sampling:1, 5, 3}
        generator.blue: ${sampling:1, 5, 3}
        altar: ${sampling:1, 5, 3}
