# Multi-room version of `left_or_right.yaml`.

defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
  num_agents: 64
  # Enough time to pick one direction, but not to dilly-dally.
  max_steps: 25
  diversity_bonus:
    enabled: true
    similarity_coef: 100  # Coefficient for within-group similarity
    diversity_coef: 100   # Coefficient for between-group diversity

  map_builder:
    _target_: metta.map.mapgen.MapGen

    width: 300
    height: 100
    border_width: 6

    root:
      _target_: metta.map.scenes.multi_left_and_right.MultiLeftAndRight
      rows: 8
      columns: 8
      total_altars: 4  # Total number of altars in each room
      altar_ratio: 0.75  # Ratio of altars that go to the side with more (e.g., 0.75 means 3:1 split)
