defaults:
  - /env/mettagrid/mettagrid@

game:
  num_agents: 16  #how many agents are in the map x2
  max_steps: 45
  agent:
    rewards:
      heart: 0.333
  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 2
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
<<<<<<< HEAD
      uri: "configs/env/mettagrid/maps/memor_training/easy.map"
=======
      uri: "configs/env/mettagrid/maps/memory_training/easy.map"
>>>>>>> 3dc22dd4fb1b95dce64b3e23eee4b2e406dcff01

  objects:
    altar:
      cooldown: 255
