defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 4
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.room.navigation.varied_terrain.VariedTerrain
      width: ${sampling:25,50,30}
      height: ${sampling:25,50,30}
      border_width: ${sampling:1,6,3}
      agents: 1
      style: maze # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
      objects:
        altar: ${sampling:30,75,50}
  objects:
        altar: ${sampling:1,3,2}
        generator: ${sampling:1,3,2}
        mine: ${sampling:1,3,2}
  objects:
    altar:
      cooldown: 25
      input_battery: 1
      output_heart: 1
      max_output: 100
      conversion_ticks: 1
      initial_items: ${sampling:0,1,0}
    generator:
      cooldown: 25
      input_ore: 1
      output_battery: 1
      max_output: 100
      conversion_ticks: 1
      initial_items: ${sampling:0,1,0}
    mine:
      cooldown: 25
      output_ore: 1
      max_output: 100
      conversion_ticks: 1
      initial_items: 1
