# Config: Central Table Layout (Overcooked-style)
defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 8
  map_builder:
    _target_: mettagrid.room.room_list.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.room.cooperation.central_table_layout.CentralTableLayout
        width: ${sampling:5,10,5}
        height: ${sampling:5,10,5}
        num_generators: ${sampling:1,4,2}
        num_altars: ${sampling:1,4,2}
        num_mines: ${sampling:1,4,2}
        agents:
          team_1: 2
        border_width: 3
      - _target_: mettagrid.room.cooperation.central_table_layout.CentralTableLayout
        width: ${sampling:5,10,5}
        height: ${sampling:5,10,5}
        num_generators: ${sampling:1,4,2}
        num_altars: ${sampling:1,4,2}
        num_mines: ${sampling:1,4,2}
        agents:
          team_2: 2
        border_width: 3
      - _target_: mettagrid.room.cooperation.central_table_layout.CentralTableLayout
        width: ${sampling:5,10,5}
        height: ${sampling:5,10,5}
        num_generators: ${sampling:1,4,2}
        num_altars: ${sampling:1,4,2}
        num_mines: ${sampling:1,4,2}
        agents:
          team_3: 2
        border_width: 3
      - _target_: mettagrid.room.cooperation.central_table_layout.CentralTableLayout
        width: ${sampling:5,10,5}
        height: ${sampling:5,10,5}
        num_generators: ${sampling:1,4,2}
        num_altars: ${sampling:1,4,2}
        num_mines: ${sampling:1,4,2}
        agents:
          team_4: 2
        border_width: 3

  objects:
    altar:
      cooldown: ${sampling:10,25,15}
      input_battery: 1
      max_output: 100
      conversion_ticks: ${sampling:10,25,15}
      initial_items: 0
    generator:
      cooldown: ${sampling:10,25,15}
      max_output: 100
      conversion_ticks: ${sampling:10,25,15}
      initial_items: 0
    mine:
      cooldown: ${sampling:10,25,15}
      max_output: 100
      conversion_ticks: 1
      initial_items: 1

