_target_: metta.env.mettagrid_env_set.MettaGridEnvSet

num_agents: 2
sampling: 1

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/cooperation/training/central_table_layout
  - /env/mettagrid/cooperation/training/confined_room_coord
  - /env/mettagrid/cooperation/training/two_rooms_coord