# Config: Central Table Layout (Overcooked-style)
defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 16
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 8
    border_width: 6

    room:
      _target_: mettagrid.room.cooperation.two_rooms_coord.TwoRoomsCoord
      width: ${sampling:5,15,10}
      height: ${sampling:5,15,10}
      num_shared_generators: ${sampling:1,4,2}
      num_altars: ${sampling:1,4,2}
      num_mines: ${sampling:1,4,2}
      agents: 2
      border_width: 2

  objects:
    altar:
      cooldown: ${sampling:10,25,15}
      input_battery: 1
      max_output: 100
      conversion_ticks: ${sampling:10,25,15}
      initial_items: 0
    generator:
      cooldown: ${sampling:10,25,15}
      max_output: 100
      conversion_ticks: ${sampling:10,25,15}
      initial_items: 0
    mine:
      cooldown: ${sampling:10,25,15}
      max_output: 100
      conversion_ticks: 1
      initial_items: 1

