defaults:
  - /env/mettagrid/mettagrid@

game:
  num_agents: 8  #how many agents are in the map x2
  max_steps: 70
  agent:
    rewards:
      heart: 0.333
  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/card_evals/find_the_best.map"

  objects:
    altar:
      hp: 30
      input_battery: 3
      output_heart: 1
      max_output: 3
      conversion_ticks: 1
      cooldown: ${sampling:1, 8, 10}
      initial_items: 0

    mine.red:
      hp: 30
      output_ore.red: 1
      color: 0
      max_output: 3
      conversion_ticks: 1
      cooldown: ${sampling:0, 8, 5}
      initial_items: 0

    mine.green:
      hp: 30
      output_ore.green: 1
      color: 0
      max_output: 3
      conversion_ticks: 1
      cooldown: ${sampling:0, 8, 5}
      initial_items: 1

    mine.blue:
      hp: 30
      output_ore.blue: 1
      color: 0
      max_output: 3
      conversion_ticks: 1
      cooldown: ${sampling:0, 8, 5}
      initial_items: 1

    generator.red:
      hp: 30
      input_ore.red: 1
      output_battery: 3
      color: 0
      max_output: 2
      conversion_ticks: 1
      cooldown: ${sampling:0, 8, 5}
      initial_items: 0

    generator.green:
      hp: 30
      input_ore.green: 1
      output_battery: 1
      color: 0
      max_output: 1
      conversion_ticks: 1
      cooldown: ${sampling:0, 8, 5}
      initial_items: 0

    generator.blue:
      hp: 30
      input_ore.blue: 1
      output_battery: 1
      color: 0
      max_output: 1
      conversion_ticks: 1
      cooldown: ${sampling:0, 8, 5}
      initial_items: 0
