defaults:
  - ../evaluator/evaluator.yaml

policy_uri: "wandb://run/v.daveey.species.sm.0"
baseline_uri: ["wandb://run/v.daveey.species.sm.0", "wandb://run/v.daveey.species.sm.0"]

evals:
  - env: env/mettagrid/cylinder
    metrics_to_log:
      - time_to_targets
      - elo

  - env: env/mettagrid/maze
    metrics_to_log:
      - time_to_targets
      - elo
