policy_uri: "wandb://run/uniform_sampling_v2_01_ms2000" 
baseline_uri: "wandb://run/uniform_sampling_v2_01_ms2000" 

#rather than a list of evals in the config, have a EvalList class, and here specify the arguments for the EvalList
#class called Eval, subclass called EvalList, compose them here

evals:
  - env: multi_room_cylinder
    metrics_to_log:
      - name: "time_to_generator"
        
  - env: multi_room_maze
    metrics_to_log:
      - name: "time_to_heart_altar"

#for mulit agent policies also going to want npcs (per eval)