defaults:
  - ../evaluator/evaluator.yaml

policy_uri: "wandb://run/v.daveey.train.spec.2"
baseline_uri: ["wandb://run/b.daveey.train.sb.6", "wandb://run/b.daveey.train.sm.6"]

evals:
  - env: env/mettagrid/cylinder
    metrics_to_log:
      - time_to_targets
      - elo

  - env: env/mettagrid/maze
    metrics_to_log:
      - time_to_targets
      - elo
