# suite/suite_config.yaml

# We can define default merges so that everything merges the base evaluator_config.
# Then each environment item in `evals` can override environment or other fields.

defaults:
  # The base evaluator config:
  - ../evaluator/evaluator.yaml

policy_uri: "wandb://run/b.daveey.train.sb.6"
baseline_uri: "wandb://run/b.daveey.train.sb.6"

evals:
  - env: env/mettagrid/cylinder
    metrics_to_log:
      - time_to_targets
      - elo

  - env: env/mettagrid/maze
    metrics_to_log:
      - time_to_targets
      - elo
