defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
  num_agents: 1 #how many agents are in the map x2
  max_steps: 200

  agent:
    rewards:
      heart: 1

  map_builder:
    _target_: mettagrid.room.ascii.Ascii
    border_width: 3
    uri: "configs/env/mettagrid/maps/sequence/es5.map"


  objects:
    altar:
      hp: 30
      input_battery.green: 1
      output_heart: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 255
      initial_items: 0

    mine.green:
      hp: 30
      input_battery.blue: 1
      output_ore.green: 1
      color: 2
      max_output: 5
      conversion_ticks: 1
      cooldown: 255
      initial_items: 0

    generator.green:
      hp: 30
      input_ore.green: 1
      output_battery.green: 1
      color: 2
      max_output: 5
      conversion_ticks: 1
      cooldown: 255
      initial_items: 0

    # mine.red:
    #   hp: 30
    #   # input_battery.blue: 1
    #   output_ore.red: 1
    #   color: 0
    #   max_output: 5
    #   conversion_ticks: 1
    #   cooldown: 255
    #   initial_items: 1

    # generator.red:
    #   hp: 30
    #   input_ore.red: 1
    #   output_battery.red: 1
    #   color: 0
    #   max_output: 5
    #   conversion_ticks: 1
    #   cooldown: 255
    #   initial_items: 0

    mine.blue:
      hp: 30
      # input_battery.blue: 1
      output_ore.blue: 1
      color: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 255
      initial_items: 1

    generator.blue:
      hp: 30
      input_ore.blue: 1
      output_battery.blue: 1
      color: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 255
      initial_items: 0
