defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 48
  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6
    rooms:
      - _target_: mettagrid.config.room.terrain_from_numpy.TerrainFromNumpy
        border_width: 1
        dir: "terrain_maps_nohearts"
        agents: 12
        team: team_1
        objects:
          altar: ${sampling:30,75,50}
      - _target_: mettagrid.config.room.terrain_from_numpy.TerrainFromNumpy
        border_width: 1
        dir: "terrain_maps_nohearts"
        agents: 12
        team: team_2
        objects:
          altar: ${sampling:30,75,50}
      - _target_: mettagrid.config.room.terrain_from_numpy.TerrainFromNumpy
        border_width: 1
        dir: "terrain_maps_nohearts"
        agents: 12
        team: team_3
        objects:
          altar: ${sampling:30,75,50}
      - _target_: mettagrid.config.room.terrain_from_numpy.TerrainFromNumpy
        border_width: 1
        dir: "terrain_maps_nohearts"
        agents: 12
        team: team_4
        objects:
          altar: ${sampling:30,75,50}
