defaults:
  - poor

game:
  num_agents: 20
  map:
    room:
      width: [20, 100, 40]
      height: [20, 100, 40]
      border: 1
      objects:
        agent: ${....num_agents}
        altar: [1, 10, 5]
        converter: [1, 10, 3]
        generator: [1, 15, 10]
        wall: [10, 100, 40]
