defaults:
  - mettagrid

game:
  num_agents: 2
  map:
    room:
      width: [20, 100, 50]
      height: [20, 100, 50]
      border: 1
      objects:
        agent: ${....num_agents}
        altar: [1, 10, 1]
        converter: [3, 30, 1]
        generator: 1
        wall: [10, 100, 40]
