defaults:
  - mettagrid

game:
  num_agents: 20
  map:
    room:
      width: [20, 100, 40] # [20, 100, 40] has often been 15
      height: [20, 100, 40] # [20, 100, 40] has often been 15 
      border: 1
      objects:
        agent: ${....num_agents}
        altar: [1, 10, 5]
        converter: [3, 30, 20] #[3, 30, 10] 
        generator: [10, 80, 20] #[10, 80, 50] 
        wall: [10, 100, 10] #[10, 100, 40] 