defaults:
  - mettagrid

game:
  num_agents: 20
  map:
    room:
      width: [20, 15, 15] # [20, 100, 40] 
      height: [20, 20, 15] # [20, 100, 40] 
      border: 1
      objects:
        agent: ${....num_agents}
        altar: [1, 10, 5]
        converter: [3, 30, 10] # Reverted to stock. AV was [3, 30, 20]
        generator: [10, 80, 20] #[10, 80, 50] 
        wall: [10, 100, 40] # Reverted to stock. AV was [10, 100, 10]