defaults:
  - mettagrid

game:
  num_agents: 20

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${div:${..num_agents},5}
    border_width: 6

    room:
      _target_: mettagrid.config.room.random.Random
      width: ${uniform:10,20,15}
      height: ${uniform:10,20,15}
      border_width: 0

      objects:
        agent: 5
        altar: ${uniform:5,5,5}
        converter: ${uniform:10,10,10}
        generator: ${uniform:30,50,50}
        wall: ${uniform:10,100,40}
