defaults:
  - mettagrid

game:
  num_agents: 20
  map:
    room:
      width: [20, 100, 40] # [20, 15, 15] restored
      height: [20, 100, 40] # [20, 20, 15] restored
      border: 1
      objects:
        agent: ${....num_agents}
        altar: [1, 10, 5]
        converter: [3, 30, 10] #[3, 30, 20] # 
        generator: [10, 80, 20] #[10, 80, 50] restored
        wall: [10, 100, 40] #[10, 10, 10] # restored