defaults:
  - mettagrid

env:
  track_last_action: false

agent:
  observation_encoder:
    track_last_action: ${env.track_last_action}

game:
  num_agents: 1
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.alternating_barriers.AlternatingBarrierMaze
    width: ${uniform:20,25,21}
    height: ${uniform:20,25,21}
    num_barriers: ${uniform:3,5,3}
    barrier_width: 1
    border_width: 1
    border_object: "wall"