# This YAML file configures the barrierdetour environment.

name: barrierdetour

# Define environment-level settings.
env:
  track_last_action: false

# Overall grid parameters.
grid:
  width: 30
  height: 25

# Outer border settings.
border:
  width: 1
  object: wall

# Define several rooms by specifying the top row, left column, width, and height.
rooms:
  - top: 5
    left: 5
    width: 7
    height: 5
  - top: 5
    left: 20
    width: 7
    height: 5
  - top: 15
    left: 5
    width: 7
    height: 5
  - top: 15
    left: 20
    width: 7
    height: 5

# Example agent configuration that uses interpolation.
# The fallback ":-false" ensures that if env.track_last_action is missing,
# the value false will be used.
agent:
  observation_encoder:
    track_last_action: ${env.track_last_action:-false}
