defaults:
  - mettagrid

# (Optional) Environment parameters used elsewhere
env:
  track_last_action: false

agent:
  observation_encoder:
    track_last_action: ${env.track_last_action}

game:
  num_agents: 1
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.barriermaze.BarrierMaze
    width: 15              # overall room width (including border)
    height: 13             # overall room height (including border)
    barrier_width: 1       # barrier thickness (in columns)
    min_barrier_height: 3  # minimum height for barriers
    max_barrier_height: 9  # maximum height for barriers
    num_barriers: 3        # number of barriers to generate
    border_width: 1        # thickness of the border walls around the environment
    border_object: "wall"  # what to fill the border with
