defaults:
  - mettagrid

game:
  num_agents: 20
  max_steps: 1200

  agent:
    rewards:
      ore: 1
      generator: 1.5
      heart: 4
      ore.max: 1000
      generator.max: 1000
      heart.max: 1000

  actions:
    swap:
      enabled: false
    change_color:
      enabled: false
    attack:
      enabled: true

  objects:
    mine.red:
      cooldown: 1000
    generator.red:
      cooldown: 200
    altar:
      cooldown: 200
      initial_items: 0
    wall:
      hp: 1
    lasery:
      output_laser: 10000
      max_output: 10000
      cooldown: 0
      initial_items: 5000


  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 5
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/break_out.map"
