
defaults:
  - mettagrid

sampling: 1


game:
  num_agents: 24

  agent:
    max_inventory: 2000
    rewards:
      # action_failure_penalty: 0.00001
      action_failure_penalty: 0
      ore.red: 0.001
      ore.blue: 0.001
      ore.green: 0.001
      battery: 0.1
      battery_max: 10
      heart: 3
      heart_max: 1000

  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,25,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,12}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,25,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,25,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          generator.blue: 1
          generator.red: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          generator.red: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          generator.blue: 1
          generator.red: 1
          altar: 1
          block: ${uniform:5,18,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          generator.blue: 1
          generator.red: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          generator.blue: 1
          generator.red: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          generator.blue: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          generator.blue: 1
          generator.red: 1
          altar: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:8,25,20}
        height: ${uniform:8,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          generator.red: 1
          generator.green: 1
          altar: 1
          block: ${uniform:5,25,20}
  objects:
    mine.red:
      hp: 30
      cooldown: 1

    mine.blue:
      hp: 30
      cooldown: 1

    mine.green:
      hp: 30
      cooldown: 1

    generator.red:
      hp: 30
      cooldown: ${uniform:5,60,40}
      output_battery: ${uniform:1,10,5}

    generator.green:
      hp: 30
      cooldown: ${uniform:5,60,40}
      output_battery: ${uniform:1,10,5}

    generator.blue:
      hp: 30
      cooldown: ${uniform:5,60,40}
      output_battery: ${uniform:1,10,5}

    altar:
      hp: 1000
      cooldown: 10
      initial_items: 0
      max_output: 10


  block:
      hp: ${uniform:1,8,3}

  actions:
    attack:
      enabled: false
    change_color:
      enabled: false
