
defaults:
  - mettagrid

sampling: 1

game:
  num_agents: 24

  agent:
    max_inventory: 2000
    rewards:
      action_failure_penalty: 0
      battery: 1
      battery_max: 1000

  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          block: ${uniform:5,25,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          block: ${uniform:5,15,12}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          block: ${uniform:5,25,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          block: ${uniform:5,25,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          block: ${uniform:5,16,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.red: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.green: 1
          block: ${uniform:5,15,20}
      - _target_: mettagrid.config.room.random.Random
        width: ${uniform:6,25,20}
        height: ${uniform:6,25,20}
        border_width: 1

        agents: 1

        objects:
          mine.red: 1
          mine.blue: 1
          mine.green: 1
          generator.blue: 1
          block: ${uniform:5,25,20}
  objects:
    mine.red:
      hp: 30
      cooldown: 1

    mine.blue:
      hp: 30
      cooldown: 1

    mine.green:
      hp: 30
      cooldown: 1

    generator.red:
      hp: 30
      cooldown: 10

    generator.green:
      hp: 30
      cooldown: 10

    generator.blue:
      hp: 30
      cooldown: 10

    block:
      hp: ${uniform:1,6,3}

  actions:
    attack:
      enabled: false
    change_color:
      enabled: false
