
defaults:
  - mettagrid

sampling: 1


game:
  num_agents: 2

  agent:
    max_inventory: 2000
    rewards:
      # action_failure_penalty: 0.00001
      action_failure_penalty: 0
      ore.red: 0.001
      ore.blue: 0.001
      ore.green: 0.001
      battery: 0.1
      battery_max: 10
      heart: 3
      heart_max: 1000

  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.config.room.random.Random
        width: 12
        height: 12 
        border_width: 1

        agents: 1

        objects:
          mine.red: 2
          mine.blue: 2
          mine.green: 2
          generator.red: 2
          generator.blue: 2
          generator.green: 2
          altar: 3
          block: ${uniform:5,25,20}

      - _target_: mettagrid.config.room.random.Random
        width: 20
        height: 20 
        border_width: 1

        agents: 1

        objects:
          mine.red: 2
          mine.blue: 2
          mine.green: 2
          generator.red: 2
          generator.blue: 2
          generator.green: 2
          altar: 3
          block: ${uniform:5,25,20}
     
  objects:
    mine.red:
      hp: 30
      cooldown: 1

    mine.blue:
      hp: 30
      cooldown: 1

    mine.green:
      hp: 30
      cooldown: 1

    generator.red:
      hp: 30
      cooldown: 10
      input_ore.red: 1
      output_battery: 6

    generator.green:
      hp: 30
      input_ore.green: 1
      cooldown: 10
      output_battery: 1

    generator.blue:
      hp: 30
      input_ore.blue: 1
      cooldown: 10
      output_battery: 1

    altar:
      hp: 1000
      cooldown: 1
      initial_items: 0
      max_output: 10

    block:
        hp: ${uniform:1,8,3}

  actions:
    attack:
      enabled: false
    change_color:
      enabled: false
