defaults:
  - mettagrid

game:
  num_agents: 2
  map:
    room:
      width: 20
      height: 20
      border: 1
      objects:
        agent: 2
        altar: 1
        converter: 1
        generator: 1
        wall: 2
  objects:
    agent:
      energy_reward: 1.0
    wall:
      hp: 100