defaults:
  - mettagrid

game:
  num_agents: 1        # One agent in the room
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.explore_exploit.ExploreExploit
    width: 30           # Reduced overall grid width
    height: 15          # Reduced overall grid height
    border_width: 1     # Thickness of the border walls
    border_object: "wall"
    explore_exploit_params:
      obstruction_gap_prob: 0.2    # Probability of a gap in the vertical obstruction wall
      sparse_min_distance: 8       # Increased minimum Manhattan distance in the sparse region
