defaults:
  - mettagrid

sampling: 1
game:
  num_agents: 2        # One agent per room
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.room_list.RoomList
    # Specify a list of room configurations (each room can have different parameters)
    rooms:
      - _target_: mettagrid.config.room.cylinder.Cylinder
        border_width: 1
        width: ${uniform:10,40,21}
        height: ${uniform:10,40,21}
        cylinder_params:
          length: ${uniform:3,5,10}
          horizontal: true | false
          both_ends: true | false
      - _target_: mettagrid.config.room.radial_maze.RadialMaze
        border_width: 1
        width: ${uniform:20,40,31}
        height: ${uniform:20,40,31}
        radial_params:
          num_arms: ${uniform:4,8,6}  # Number of arms in the radial maze
          arm_length: ${uniform:5,10,8}  # Length of each arm
          center_radius: ${uniform:2,4,3}  # Radius of the central area
          num_generators: 2  # Number of arms that will end with a generator
          num_convertors: 2  # Number of arms that will end with a convertor
          num_heart_altars: 2  # Number of arms that will end with a heart altar
        