defaults:
  - mettagrid

sampling: 1
game:
  num_agents: 5        # One agent per room (five rooms in total)
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.room_list.RoomList
    # List of room configurations
    rooms:
      - _target_: mettagrid.config.room.cylinder.Cylinder
        border_width: 1
        width: ${uniform:10,40,21}
        height: ${uniform:10,40,21}
        cylinder_params:
          length: ${uniform:3,5,10}
          horizontal: true | false
          both_ends: true | false

      - _target_: mettagrid.config.room.radial_maze.RadialMaze
        border_width: 1
        width: ${uniform:20,40,31}
        height: ${uniform:20,40,31}
        radial_params:
          num_arms: ${uniform:4,8,6}        # Number of arms in the radial maze
          arm_length: ${uniform:5,10,8}       # Length of each arm
          center_radius: ${uniform:2,4,3}     # Radius of the central area

      - _target_: mettagrid.config.room.alternating_barriers.AlternatingBarrierMaze
        width: 24            # Overall grid width (including border)
        height: 14           # Overall grid height (including border)
        barrier_width: 1     # Barrier thickness (in columns)
        barrier_heights: [5, 7, 9]  # List of barrier heights (one per barrier)
        border_width: 1      # Thickness of the outer border walls
        border_object: "wall"

      - _target_: mettagrid.config.room.explore_exploit.ExploreExploit
        width: 30           # Overall grid width for explore_exploit
        height: 15          # Overall grid height for explore_exploit
        border_width: 1
        border_object: "wall"
        explore_exploit_params:
          obstruction_gap_prob: 0.2    # Probability of a gap in the vertical obstruction wall
          sparse_min_distance: 8       # Increased minimum Manhattan distance in the sparse region

      - _target_: mettagrid.config.room.multi_chamber_room.MultiChamberRoom
        width: 30          # Overall grid width
        height: 30         # Overall grid height (enough for 4 chambers and 3 barriers)
        border_width: 1    # Thickness of outer border walls
        border_object: "wall"
        multi_chamber_params:
          barrier_rows: [8, 16, 24]  # Rows where horizontal barriers are drawn
          gap_width: 4                # Width of each gap (gaps will be randomized)
          chambers:
            top: "agent.agent"       # Top chamber: Agent
            second: "generator"      # Second chamber: Generator
            third: "converter"       # Third chamber: Converter
            bottom: "altar"          # Bottom chamber: Heart Altar
