defaults:
  - mettagrid

game:
  num_agents: 1
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.grok.Grok
    width: 40
    height: 40
    grok_params:
      near_enclosure_width: 6       # width of the enclosure in the near region
      near_enclosure_height: 6      # height of the enclosure in the near region
      near_generator_count: 2       # how many generators to place inside the enclosure