defaults:
  - mettagrid

env:
  track_last_action: false

agent:
  observation_encoder:
    track_last_action: ${env.track_last_action}

game:
  num_agents: 1
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.labyrinth.LabyrinthMaze
    width: 41           # Desired overall maze width (should be of the form: cell_cols*(corridor_width+1)+1)
    height: 41          # Desired overall maze height (same form as above)
    corridor_width: 3   # Width of the corridors (passages); default is 3.
    border_width: 1     # Outer border thickness (will remain walls)
    border_object: "wall"
