defaults:
  - mettagrid

game:
  num_agents: 1
  max_steps: 1000

  map_builder:
    _target_: mettagrid.config.room.manycylinder.ManyCylinder
    width: 80                # Overall grid width
    height: 40               # Overall grid height
    border_width: 1          # Wall thickness for cylinders
    num_cylinders: 10        # How many cylinders to attempt to place
    cylinder_params:
      length: 15             # For horizontal cylinders: horizontal length;
                             # for vertical cylinders: vertical extent.
      cylinder_width: 10     # For horizontal cylinders: vertical size;
                             # for vertical cylinders: horizontal size.
    seed: 42
