defaults:
  - mettagrid

game:
  num_agents: 7
  map:
    uri: configs/env/mettagrid/maps/mazes/multiroom_maze_35x27_numagents_6.map
  objects:
    altar:
      cooldown: 255
    agent:
      initial_energy: 255
  
