defaults:
  - mettagrid

game:
  num_agents: 1
  map:
    uri: configs/env/mettagrid/maps/cylinders/cylinder_21x20.map
  objects:
    altar:
      cooldown: 255
    agent:
      initial_energy: 255
  
