defaults:
  - mettagrid

game:
  num_agents: 3
  map:
    uri: configs/env/mettagrid/maps/cylinders/multiroom_cylinder_69x24_agents_3.map
  objects:
    altar:
      cooldown: 255
    agent:
      initial_energy: 255
  
