name: "GDY-MettaGrid"
_target_: mettagrid.mettagrid_env.MettaGridEnv

report_stats_interval: 100
normalize_rewards: false
flatten_actions: true
compact_obs: false

sampling: 0

hidden_features:
  grid_obs: [
    "agent:energy",
    "agent:hp",
  ]

game:
  # _target_: env.griddly.mettagrid.game_builder.MettaGridGameBuilder
  obs_width: 11
  obs_height: 11
  max_steps: 1000
  tile_size: 16
  num_agents: ???
  no_energy_steps: 500

  objects:
    agent:
      initial_energy: [0, 180, 180]
      max_energy: [0, 250, 250]
      max_inventory: [0, 10, 5]
      freeze_duration: [0, 0, 0]
      energy_reward: 0.0
      hp: 10
      mortal: False
      upkeep.time: [0, 0, 0]
      upkeep.shield: [0, 0, 0]
      use_cost: 0

    altar:
      hp: 30
      cooldown: [1, 10, 2]
      use_cost: [20, 100, 91]

    converter:
      hp: 30
      cooldown: [1, 1, 1]
      energy_output.r1: [10, 250, 150]
      energy_output.r2: [10, 100, 10]
      energy_output.r3: [1, 10, 1]

    generator:
      hp: 30
      cooldown: [0, 1, 1]
      initial_resources: [1, 150, 150]
      use_cost: 0

    wall:
      hp: [1, 20, 10]

  actions:
    noop:
      enabled: true
      cost: 0
    move:
      enabled: true
      cost: 0
    rotate:
      enabled: true
      cost: 0
    jump:
      enabled: false
      cost: 0
    shield:
      enabled: true
      cost: 0
    transfer:
      enabled: false
      cost: 0
    use:
      enabled: true
      cost: 0
    attack:
      enabled: true
      cost: 251
      damage: 50
    gift:
      enabled: true
      cost: 0
    swap:
      enabled: true
      cost: 0

  map:
    # _target_: env.griddly.mettagrid.level_builder.MettaGridLevelBuilder

    layout:
      rooms_x: 1
      rooms_y: 1

    border: 0

    room:
      # _target_: env.griddly.mettagrid.level_builder.MettaGridRoomBuilder
      width: 10
      height: 10
      objects:
        agent: 5
        altar: 5
        converter: 20
        generator: 20
        wall: 10

kinship:
  # _target_: env.wrapper.reward_sharing.TeamRewardSharing
  team_size: 1
  team_reward: 0
