defaults:
  - mettagrid

game:
  num_agents: 16  #how many agents are in the map x2


  objects:
    altar:
      cooldown: 1

    mine.red:
      cooldown: 1

    generator.red:
      cooldown: 1

  actions:
    attack:
      enabled: false
    change_color:
      enabled: false
    swap:
      enabled: false


  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 1
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/minimal_general.map"
