defaults:
  - mettagrid

game:
  num_agents: 2  #how many agents are in the map x2
  
  # actions: #which actions should be disabled in this map? 
  #   attack:
  #     enabled: false
  #   change_color:
  #     enabled: false
  #   swap:
  #     enabled: true


  objects:
    altar:
      hp: 30
      input_battery: 1
      output_heart: 1
      max_output: 30
      conversion_ticks: 1
      cooldown: 1000
      initial_items: 1

    mine.red:
      hp: 30
      output_ore.red: 1
      color: 0
      max_output: 30
      conversion_ticks: 1
      cooldown: 1000
      initial_items: 1

    generator.red:
      hp: 30
      input_ore.red: 1
      output_battery: 1
      color: 0
      max_output: 30
      conversion_ticks: 1
      cooldown: 1000
      initial_items: 1



  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 1
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/minimal_super_simple_large.map"
