defaults:
  - mettagrid

env:
  track_last_action: false

agent:
  observation_encoder:
    track_last_action: ${env.track_last_action}

game:
  num_agents: 1
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.nested_rooms.NestedRoomsMaze
    width: 60           # Overall grid width (including border)
    height: 40          # Overall grid height (including border)
    num_rooms: 5        # (Will be capped to 3 in the code)
    door_size: 3        # Size (in cells) of the gap (door) in each room's wall
    agent_in_innermost: true  # Agent is placed in the innermost room; rewards in outermost room.
    border_width: 1     # Outer border thickness (the outermost room is 1 thick)
    border_object: "wall"
