defaults:
  - mettagrid

game:
  num_agents: 32  #how many agents are in the map x2
  
  actions: #which actions should be disabled in this map? 
    attack:
      enabled: false
    change_color:
      enabled: false
    swap:
      enabled: false

  objects: #i think we should not have hearts initially in the altar but we can play with this
    altar:
      initial_items: 0


  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 2
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/MAP_NAME.map"
