defaults:
  - mettagrid

game:
  objects:
    agent:
      initial_energy: [0, 250, 100]
      max_energy: [0, 250, 250]
      max_inventory: [0, 10, 5]
      freeze_duration: [0, 200, 10]
      energy_reward: 0.0
      hp: 10
      mortal: False
      upkeep.time: [0, 3, 0]
      upkeep.shield: [0, 3, 1]
      use_cost: 0

    altar:
      hp: 30
      cooldown: [1, 10, 3]
      use_cost: [20, 100, 100]

    converter:
      hp: 30
      cooldown: [1, 20, 2]
      energy_output.r1: [10, 100, 50]
      energy_output.r2: [10, 100, 10]
      energy_output.r3: [1, 10, 1]

    generator:
      hp: 30
      cooldown: [0, 30, 20]
      initial_resources: [1, 30, 10]
      use_cost: 0

    wall:
      hp: [1, 20, 10]

  map:
    # _target_: env.griddly.mettagrid.level_builder.MettaGridLevelBuilder

    layout:
      rooms_x: 1
      rooms_y: 1

    room:
      # _target_: env.griddly.mettagrid.level_builder.MettaGridRoomBuilder
      width: 25
      height: 25
      objects:
        agent: 5
        altar: 1
        converter: 3
        generator: 15
        wall: 10

kinship:
  # _target_: env.wrapper.reward_sharing.TeamRewardSharing
  team_size: 1
  team_reward: 0
