
defaults:
  - mettagrid

game:
  num_agents: 24

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${div:${..num_agents},6}
    border_width: 1

    room:
      _target_: mettagrid.config.room.random.Random
      width: ${uniform:10,100,14}
      height: ${uniform:10,100,14}
      border_width: 0

      agents: 6

      objects:
        mine: ${uniform:1,10,10}
        generator: ${uniform:1,10,10}
        altar: ${uniform:1,5,7}
        armory: ${uniform:0,5,1}
        lasery: ${uniform:0,5,1}
        lab: ${uniform:0,5,1}
        factory: ${uniform:0,5,1}
        temple: ${uniform:0,5,1}

        wall: ${uniform:1,100,1}


