

defaults:
  - mettagrid

game:
  num_agents: 24

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${div:${..num_agents},6}
    border_width: 1

    room:
      _target_: mettagrid.config.room.random.Random
      width: 10
      height: 10
      border_width: 0

      agents: 6

      objects:
        mine: 10
        generator: 10
        altar: 7
        armory: 0
        lasery: 0
        lab: 0
        factory: 0
        temple: 0

        wall: 1
