name: "GDY-MettaGrid"
_target_: mettagrid.mettagrid_env.MettaGridEnv


defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

envs:
  - /env/mettagrid/simple

game:
  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    put_items:
      enabled: true
    get_items:
      enabled: true
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false
