defaults:
  - mettagrid

game:
  num_agents: 1
  max_steps: 1000

  map_builder:
    _target_: mettagrid.config.room.spiral_maze.SpiralMaze
    width: 80               # Overall grid width
    height: 80              # Overall grid height
    border_width: 1         # Outer border thickness (remains as walls)
    corridor_width: 2       # Thickness of the spiral corridor (try 1 or 2)
    resource_density: 0.5   # Base probability for placing a resource in a corridor cell (highest at the center)
    seed: 42
