defaults:
  - mettagrid

sampling: 1

game:
  num_agents: 40
  map:
    room:
      width: [5, 75, 25]
      height: [5, 75, 25]
      border: 1
      objects:
        agent: ${....num_agents}
        altar: [1, 20, 8]
        converter: [3, 25, 10]
        generator: [10, 60, 40]
        wall: [10, 50, 30]
  objects:
    energy_reward: 1.0