# Configuration file for the barrierdetour environment

name: ushapebarrier

grid:
  width: 30
  height: 25

border:
  width: 1
  object: wall

# Define a single room. Modify top, left, width, and height as needed.
rooms:
  - top: 5
    left: 5
    width: 7
    height: 5
