defaults:
  - mettagrid

game:
  num_agents: 6
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${..num_agents}
    room:
      _target_: mettagrid.config.room.ymaze.YMaze
      border_width: 1
      width: ${uniform:20,40,30}      # Grid width sampled between 20 and 40 (default 30)
      height: ${uniform:20,40,30}     # Grid height sampled between 20 and 40 (default 30)
      # Remove any "place_agents" flag here so that YMaze uses its default behavior.
      ymaze_params:
        stem_length: ${uniform:3,15,7}
        arm_length: ${uniform:2,9,4}
        sensory_range: ${uniform:2,8,4}
