# File: mettagrid/config/room/zigzag_room.yaml

_target_: mettagrid.config.room.zigzag_room.ZigZagRoom
width: 30             # Overall grid width
height: 30            # Overall grid height
border_width: 1       # Thickness of outer border walls
zigzag_params:
  num_zigs: 4         # Number of zigzag segments
  amplitude: 3        # Horizontal extent of each zigzag segment
  frequency: 2        # Number of rows before switching direction
