defaults:
  - agent: simple
  - env/mettagrid@env: simple
  - trainer: puffer
  - sweep: full
  - hardware: macbook
  - eval: simple
  - analyzer: train_analyzer

seed: 1
eval_db_uri: null
run: ???
data_dir: ./train_dir
run_dir: ${data_dir}/${run}

torch_deterministic: true
vectorization: multiprocessing
dashboard: false

wandb:
  enabled: true
  track: true
  project: metta
  entity: metta-research
  group: ${run}
  name: ${run}
