defaults:
  - common
  - wandb: metta_research
  - sim: simple
  - _self_

cmd: play
run: ???
data_dir: ./train_dir
eval_db_uri: null

torch_deterministic: true

play_job:
  sim: ${sim}
  policy_uri: ${policy_uri}
