defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 24
  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
        width: ${sampling:50,120,100}
        height: ${sampling:50,120,100}
        border_width: ${sampling:1,6,3}
        agents: 6
        style: all-sparse # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
        teams: [team_1]
        objects:
          altar: ${sampling:10,20,15}
      - _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
        width: ${sampling:50,120,100}
        height: ${sampling:50,120,100}
        border_width: ${sampling:1,6,3}
        agents: 6
        style: all-sparse # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
        teams: [team_2]
        objects:
          altar: ${sampling:10,20,15}
      - _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
        width: ${sampling:50,120,100}
        height: ${sampling:50,120,100}
        border_width: ${sampling:1,6,3}
        agents: 6
        style: all-sparse # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
        teams: [team_3]
        objects:
          altar: ${sampling:10,20,15}
      - _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
        width: ${sampling:50,120,100}
        height: ${sampling:50,120,100}
        border_width: ${sampling:1,6,3}
        agents: 6
        style: all-sparse # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
        teams: [team_4]
        objects:
          altar: ${sampling:10,20,15}
