defaults:
  - mettagrid

game:
  num_agents: 4
  map:
    rooms: 
      - _target_: deps.mettagrid.mettagrid.config.maze_builder.MazeRoom
        width: 25
        height: 25
        start_pos: [1, 1]  # Note: Use array syntax instead of tuple
        end_pos: [23, 23]
        branching: 0.6
      - _target_: deps.mettagrid.mettagrid.config.maze_builder.MazeRoom
        width: 24
        height: 24
        start_pos: [1, 1]
        end_pos: [23, 23]
        branching: 0.6
      - _target_: deps.mettagrid.mettagrid.config.maze_builder.MazeRoom
        width: 20
        height: 20
        start_pos: [1, 1]
        end_pos: [23, 23]
        branching: 0.6
      - _target_: deps.mettagrid.mettagrid.config.maze_builder.MazeRoom
        width: 25
        height: 25
        start_pos: [1, 1]
        end_pos: [23, 23]
        branching: 0.6
  objects:
    altar:
      cooldown: 255
    agent:
      initial_energy: 255
  
