game:
  num_agents: 4
  map:
    rooms: 
      - _target_: deps.mettagrid.mettagrid.config.cylinder_builder.CylinderRoom
        width: 25
        height: 25
        num_agents: 1
        cylinder_params:
          length: 10
          orientation: horizontal
          both_ends: true
      - _target_: deps.mettagrid.mettagrid.config.cylinder_builder.CylinderRoom
        width: 25
        height: 25
        num_agents: 1
        cylinder_params:
          length: 10
          orientation: horizontal
          both_ends: true
      - _target_: deps.mettagrid.mettagrid.config.cylinder_builder.CylinderRoom
        width: 25
        height: 25
        num_agents: 1
        cylinder_params:
          length: 10
          orientation: vertical
          both_ends: true
      - _target_: deps.mettagrid.mettagrid.config.cylinder_builder.CylinderRoom
        width: 25
        height: 25
        num_agents: 1
        cylinder_params:
          length: 10
          orientation: vertical
          both_ends: true
  objects:
    altar:
      cooldown: 255
    agent:
      initial_energy: 255
  
