defaults:
  - /env/mettagrid/mettagrid@

sampling: 1
game:
  num_agents: 24    #how many agents are in the map x2

  agent:
    max_inventory: 5

  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.config.room.terrain_from_numpy.TerrainFromNumpy
        border_width: 1
        dir: "terrain_maps_nohearts"
        agents: 6
        team: team_1
        objects:
          altar: ${sampling:10,75,30}
      - _target_: mettagrid.config.room.terrain_from_numpy.TerrainFromNumpy
        border_width: 1
        dir: "terrain_maps_nohearts"
        agents: 6
        team: team_2
        objects:
          altar: ${sampling:10,75,30}
      - _target_: mettagrid.config.room.terrain_from_numpy.TerrainFromNumpy
        border_width: 1
        dir: "terrain_maps_nohearts"
        agents: 6
        team: team_3
        objects:
          altar: ${sampling:10,75,30}
      - _target_: mettagrid.config.room.terrain_from_numpy.TerrainFromNumpy
        border_width: 1
        dir: "terrain_maps_nohearts"
        agents: 6
        team: team_4
        objects:
          altar: ${sampling:10,75,30}

  reward_sharing:
    groups:
      team_1:
        team_1: 0.6
      team_2:
        team_2: 0.6
      team_3:
        team_3: 0.6
      team_4:
        team_4: 0.6
