defaults:
  - sim
  - _self_

name: all

simulations:
  navigation/emptyspace_withinsight:
    env: env/mettagrid/navigation/evals/emptyspace_withinsight
  navigation/emptyspace_outofsight:
    env: env/mettagrid/navigation/evals/emptyspace_outofsight
  navigation/emptyspace_sparse:
    env: env/mettagrid/navigation/evals/emptyspace_sparse
  navigation/walls_withinsight:
    env: env/mettagrid/navigation/evals/walls_withinsight
  navigation/walls_outofsight:
    env: env/mettagrid/navigation/evals/walls_outofsight
  navigation/walls_sparse:
    env: env/mettagrid/navigation/evals/walls_sparse
  navigation/cylinder:
    env: env/mettagrid/navigation/evals/cylinder
  navigation/obstacles0:
    env: env/mettagrid/navigation/evals/obstacles0
  navigation/obstacles1:
    env: env/mettagrid/navigation/evals/obstacles1
  navigation/obstacles2:
    env: env/mettagrid/navigation/evals/obstacles2
  navigation/obstacles3:
    env: env/mettagrid/navigation/evals/obstacles3
  navigation/corridors:
    env: env/mettagrid/navigation/evals/corridors
  navigation/labyrinth:
    env: env/mettagrid/navigation/evals/labyrinth
  navigation/radialmaze:
    env: env/mettagrid/navigation/evals/radialmaze
    policy_agents_pct: 1.0
  memory/easy:
    env: env/mettagrid/memory/evals/easy
    policy_agents_pct: 1.0
  memory/medium:
    env: env/mettagrid/memory/evals/medium
    policy_agents_pct: 1.0
  memory/hard:
    env: env/mettagrid/memory/evals/hard
    policy_agents_pct: 1.0
  multiagent/choose_altar_team:
    env: env/mettagrid/multiagent/evals/choose_an_altar_team
    policy_agents_pct: 1.0
  multiagent/choose_an_altar:
    env: env/mettagrid/multiagent/evals/choose_an_altar
    policy_agents_pct: 1.0
  multiagent/circambulate:
    env: env/mettagrid/multiagent/evals/circambulate
    policy_agents_pct: 1.0
  multiagent/circambulate_team:
    env: env/mettagrid/multiagent/evals/circambulate_team
    policy_agents_pct: 1.0
  multiagent/corridor:
    env: env/mettagrid/multiagent/evals/corridor
    policy_agents_pct: 1.0
  multiagent/corridor_team:
    env: env/mettagrid/multiagent/evals/corridor_team
    policy_agents_pct: 1.0
  multiagent/fork:
    env: env/mettagrid/multiagent/evals/fork
    policy_agents_pct: 1.0
  multiagent/fork_team:
    env: env/mettagrid/multiagent/evals/fork_team
    policy_agents_pct: 1.0
  multiagent/protect_the_resources:
    env: env/mettagrid/multiagent/evals/protect_the_resources
    policy_agents_pct: 1.0
  multiagent/radial_cross:
    env: env/mettagrid/multiagent/evals/radial_cross
    policy_agents_pct: 1.0
  multiagent/radial_cross_large:
    env: env/mettagrid/multiagent/evals/radial_cross_large
    policy_agents_pct: 1.0
  multiagent/radial_diffusions:
    env: env/mettagrid/multiagent/evals/radial_diffusion
    policy_agents_pct: 1.0
  multiagent/spine_maze_extended:
    env: env/mettagrid/multiagent/evals/spine_maze_extended
    policy_agents_pct: 1.0
<<<<<<< HEAD
  multiagent/stealing:
    env: env/mettagrid/multiagent/evals/stealing
    policy_agents_pct: 1.0
  multiagent/team_up:
    env: env/mettagrid/multiagent/evals/team_up
    policy_agents_pct: 1.0
  multiagent/wallblocker_team:
    env: env/mettagrid/multiagent/evals/wallblocker_team
    policy_agents_pct: 1.0
  multiagent/wallblocker:
    env: env/mettagrid/multiagent/evals/wallblocker
    policy_agents_pct: 1.0
  simple_npc:
=======
  npc/simple:
>>>>>>> 79b1ec2c6339cd79b843d7c5422c00fe8538d841
    env: env/mettagrid/simple
    policy_agents_pct: 0.5
    npc_policy_uri: wandb://run/b.alex.robust.npc.s.s.004
  object_use/altar_use_free:
    env: env/mettagrid/object_use/evals/altar_use_free
    policy_agents_pct: 1.0
  object_use/altar_use:
    env: env/mettagrid/object_use/evals/altar_use
    policy_agents_pct: 1.0
  object_use/armory_use_free:
    env: env/mettagrid/object_use/evals/armory_use_free
    policy_agents_pct: 1.0
  object_use/armory_use:
    env: env/mettagrid/object_use/evals/armory_use
    policy_agents_pct: 1.0
  object_use/generator_use_free:
    env: env/mettagrid/object_use/evals/generator_use_free
    policy_agents_pct: 1.0
  object_use/generator_uses:
    env: env/mettagrid/object_use/evals/generator_use
    policy_agents_pct: 1.0
  object_use/lasery_use_free:
    env: env/mettagrid/object_use/evals/lasery_use_free
    policy_agents_pct: 1.0
  object_use/lasery_use:
    env: env/mettagrid/object_use/evals/lasery_use
    policy_agents_pct: 1.0
  object_use/mine_use:
    env: env/mettagrid/object_use/evals/mine_use
    policy_agents_pct: 1.0
  object_use/shoot_out:
    env: env/mettagrid/object_use/evals/shoot_out
    policy_agents_pct: 1.0
  object_use/swap_in:
    env: env/mettagrid/object_use/evals/swap_in
    policy_agents_pct: 1.0
  object_use/swap_out:
    env: env/mettagrid/object_use/evals/swap_out
    policy_agents_pct: 1.0
  object_use/temple_use_free:
    env: env/mettagrid/object_use/evals/temple_use_free
    policy_agents_pct: 1.0
  object_use/full_sequence:
    env: env/mettagrid/object_use/evals/full_sequence
