defaults:
  - sim
  - _self_

name: daphne
simulations:
  choose_an_altar_team:
    env: env/mettagrid/multiagent/evals/be_polite
  multiagent:
    env: env/mettagrid/multiagent/training/reward_sharing/48_range/varied_terrain_all_sparse
