defaults:
  - sim_suite
  - _self_

name: extended_sequence

simulations:
  extended_sequence/es1:
    env: env/mettagrid/object_use/extended_sequence_evals/es1
  extended_sequence/es2:
    env: env/mettagrid/object_use/extended_sequence_evals/es2
  extended_sequence/es3:
    env: env/mettagrid/object_use/extended_sequence_evals/es3
  extended_sequence/es4:
    env: env/mettagrid/object_use/extended_sequence_evals/es4
  extended_sequence/es5:
    env: env/mettagrid/object_use/extended_sequence_evals/es5
  extended_sequence/es6:
    env: env/mettagrid/object_use/extended_sequence_evals/es6
  extended_sequence/es7:
    env: env/mettagrid/object_use/extended_sequence_evals/es7
