defaults:
  - sim
  - _self_

num_envs: 1
num_episodes: 1
run_dir: ${run_dir}

simulations:
  navigation/memory_easy:
    env: env/mettagrid/navigation/evals/memory_easy_eval
    policy_agents_pct: 1.0
  navigation/memory_medium:
    env: env/mettagrid/navigation/evals/memory_medium_eval
    policy_agents_pct: 1.0
  navigation/memory_hard:
    env: env/mettagrid/navigation/evals/memory_hard_eval
    policy_agents_pct: 1.0
 
