defaults:
  - sim
  - _self_

num_envs: 1
num_episodes: 1
run_dir: ${run_dir}

simulations:
  memory/easy:
    env: env/mettagrid/memory/evals/easy
    policy_agents_pct: 1.0
  memory/medium:
    env: env/mettagrid/memory/evals/medium
    policy_agents_pct: 1.0
  memory/hard:
    env: env/mettagrid/memory/evals/hard
    policy_agents_pct: 1.0
  memory/in_view:
    env: env/mettagrid/memory/evals/in_view
    policy_agents_pct: 1.0
