defaults:
  - sim
  - _self_

simulations:
  memory/easy:
    env: env/mettagrid/memory/evals/easy
    policy_agents_pct: 1.0
  memory/medium:
    env: env/mettagrid/memory/evals/medium
    policy_agents_pct: 1.0
  memory/hard:
    env: env/mettagrid/memory/evals/hard
    policy_agents_pct: 1.0
  memory/mini_zop:
    env: env/mettagrid/memory/evals/mini_zop
    policy_agents_pct: 1.0
  memory/quantity:
    env: env/mettagrid/memory/evals/quantity_1
    policy_agents_pct: 1.0
  memory/ultra_hard:
    env: env/mettagrid/memory/evals/ultra_hard
    policy_agents_pct: 1.0
