defaults:
  - sim_suite
  - _self_

name: multiagent

simulations:
  multiagent/radial_cross_1:
    env: env/mettagrid/multiagent/evals/radial_cross
    npc_policy_uri: wandb://run/radial_cross_npc
    policy_agents_pct: 0.5
  multiagent/radial_cross_2:
    env: env/mettagrid/multiagent/evals/radial_cross
    npc_policy_uri: wandb://run/radial_cross_npc2
    policy_agents_pct: 0.5
  multiagent/radial_cross_3:
    env: env/mettagrid/multiagent/evals/radial_cross
    npc_policy_uri: wandb://run/radial_cross_npc2
    policy_agents_pct: 0.8

  multiagent/radial_cross_large:
    env: env/mettagrid/multiagent/evals/radial_cross_large
  multiagent/radial_diffusion:
    env: env/mettagrid/multiagent/evals/radial_diffusion
  multiagent/spine_maze_extended:
    env: env/mettagrid/multiagent/evals/spine_maze_extended
