defaults:
  - sim
  - _self_

num_envs: 1
num_episodes: 1
run_dir: ${run_dir}

simulations:
  multiagent/spreading_across:
    env: env/mettagrid/multiagent/evals/radial_cross
    policy_agents_pct: 1.0
  multiagent/spreading_diffusion:
    env: env/mettagrid/multiagent/evals/radial_diffusion
    policy_agents_pct: 1.0
  multiagent/spreading_maze:
    env: env/mettagrid/multiagent/evals/spine_maze_extended
    policy_agents_pct: 1.0
  multiagent/spreading_circambulate:
    env: env/mettagrid/multiagent/evals/circambulate
    policy_agents_pct: 1.0
  multiagent/spreading_corridor:
    env: env/mettagrid/multiagent/evals/corridor
    policy_agents_pct: 1.0
  multiagent/nonuniform_fork:
    env: env/mettagrid/multiagent/evals/fork
    policy_agents_pct: 1.0
  multiagent/choose_an_altar:
    env: env/mettagrid/multiagent/evals/choose_an_altar
    policy_agents_pct: 1.0
  multiagent/circumbulate_team:
    env: env/mettagrid/multiagent/evals/circumbulate_team
    policy_agents_pct: 1.0
  multiagent/imitation_game:
    env: env/mettagrid/multiagent/evals/imitation_game
    policy_agents_pct: 1.0
  multiagent/protect_the_resources:
    env: env/mettagrid/multiagent/evals/protect_the_resources
    policy_agents_pct: 1.0
  multiagent/whichway:
    env: env/mettagrid/multiagent/evals/whichway
    policy_agents_pct: 1.0
