defaults:
  - sim_suite
  - _self_

name: all

simulations:
  navigation/emptyspace_withinsight:
    env: env/mettagrid/navigation/evals/emptyspace_withinsight
  navigation/emptyspace_outofsight:
    env: env/mettagrid/navigation/evals/emptyspace_outofsight
  navigation/emptyspace_sparse:
    env: env/mettagrid/navigation/evals/emptyspace_sparse
  navigation/walls_withinsight:
    env: env/mettagrid/navigation/evals/walls_withinsight
  navigation/walls_outofsight:
    env: env/mettagrid/navigation/evals/walls_outofsight
  navigation/walls_sparse:
    env: env/mettagrid/navigation/evals/walls_sparse
  navigation/cylinder:
    env: env/mettagrid/navigation/evals/cylinder
  navigation/obstacles0:
    env: env/mettagrid/navigation/evals/obstacles0
  navigation/obstacles1:
    env: env/mettagrid/navigation/evals/obstacles1
  navigation/obstacles2:
    env: env/mettagrid/navigation/evals/obstacles2
  navigation/obstacles3:
    env: env/mettagrid/navigation/evals/obstacles3
  navigation/corridors:
    env: env/mettagrid/navigation/evals/corridors
  navigation/labyrinth:
    env: env/mettagrid/navigation/evals/labyrinth
  navigation/radialmaze:
    env: env/mettagrid/navigation/evals/radialmaze
    policy_agents_pct: 1.0
  object_use/generator/generator_use_free:
    env: env/mettagrid/object_use/generator/evals/generator_use_free