defaults:
  - sim
  - _self_

name: navigation

simulations:
  navigation/emptyspace_withinsight:
    env: env/mettagrid/navigation/evals/emptyspace_withinsight
  navigation/emptyspace_outofsight:
    env: env/mettagrid/navigation/evals/emptyspace_outofsight

# selector_type: "latest"
