defaults:
  - /env/mettagrid/memory/evals/defaults@

game:
  num_agents: 8  #how many agents are in the map x2
  max_steps: 90
  agent:
    rewards:
      heart: 1
  map_builder:

    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 4
    room:
      _target_: mettagrid.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/memory/journey_home.map"

  objects:
    altar:
      cooldown: 255
