defaults:
  - /env/mettagrid/memory/evals/defaults@

game:
  max_steps: 70
  agent:
    rewards:
      heart: 0.333
  map_builder:
    uri: "configs/env/mettagrid/maps/memory/little_landmark_easy.map"
