defaults:
  - /env/mettagrid/memory/evals/defaults@

game:
  max_steps: 110
  agent:
    rewards:
      heart: 100
  map_builder:
    uri: "configs/env/mettagrid/maps/memory/little_landmark_easy.map"
