defaults:
  - /env/mettagrid/memory/evals/defaults@

game:
  num_agents: 2  #how many agents are in the map x2
  max_steps: 100
  map_builder:
    uri: "configs/env/mettagrid/maps/memory/lobster_legs_cues.map"
