defaults:
  - /env/mettagrid/memory/evals/defaults@

game:
  num_agents: 2
  max_steps: 58
  map_builder:
    uri: "configs/env/mettagrid/maps/memory/medium.map"
  objects:
    altar:
      initial_items: 1
