defaults:
  - /env/mettagrid/memory/evals/defaults@

game:
  num_agents: 2
  max_steps: 100
  agent:
    rewards:
      heart: 0.333
  map_builder:
    uri: "configs/env/mettagrid/maps/memory/you_shall_not_pass.map"
