
defaults:
  - mettagrid

game:
  num_agents: 1

  agent:
    rewards:
      ore.red: 1
      ore.red_max: 1

  map_builder:
    _target_: mettagrid.config.room.matrix.Matrix
    rows: 5
    cols: 5
    room_width: 6
    room_height: 6
    door_gap: 1

