defaults:
  - /env/mettagrid/multiagent/evals/defaults@
  - _self_

game:
  num_agents: 8 #how many agents are in the map x2
  max_steps: 70
  agent:
    rewards:
      heart: 1.0
  map_builder:
    uri: "configs/env/mettagrid/maps/multiagent/radial_diffusion.map"
