defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
  num_agents: 6 #how many agents are in the map x2
  max_steps: 70

  agent:
    rewards:
      heart: 1

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 1
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/multiagent/spine_maze_extended.map"

  objects:
    altar:
      cooldown: 255
