defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
  num_agents: 80 #how many agents are in the map x2
  max_steps: 500

  agent:
    rewards:
      heart: 0.2

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 20
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/multiagent/stealing.map"

  objects:
    altar:
      cooldown: 30
      max_output: 5
      initial_items: 0

    mine.red:
      hp: 30
      output_ore.red: 1
      color: 0
      max_output: 5
      conversion_ticks: 1
      cooldown: 20 #${sampling:0, 100, 50}
      initial_items: 1

    mine.green:
      hp: 30
      output_ore.green: 1
      color: 2
      max_output: 5
      conversion_ticks: 1
      cooldown: 20 #${sampling:0, 100, 50}
      initial_items: 1

    generator.red:
      hp: 30
      input_ore.red: 1
      output_battery: 1
      color: 0
      max_output: 5
      conversion_ticks: 1
      cooldown: 0 #${sampling:0, 50, 25}
      initial_items: 1

    generator.green:
      hp: 30
      input_ore.green: 1
      output_battery: 1
      color: 2
      max_output: 5
      conversion_ticks: 1
      cooldown: 0 #${sampling:0, 50, 25}
      initial_items: 1
