defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
  num_agents: 40 #how many agents are in the map x2
  max_steps: 38

  agent:
    rewards:
<<<<<<< HEAD
      heart: 0.333333
=======
      heart: 0.333
>>>>>>> 4c0f0c867242b30fc85628959a559293f6a0ca62

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 20
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/multiagent/wallblocker.map"

  objects:
    altar:
      cooldown: 255
