defaults:
  - /env/mettagrid/multiagent/evals/defaults@
  - _self_

game:
  num_agents: 2 #how many agents are in the map x2
  max_steps: 38
  agent:
    rewards:
      heart: 0.333
  map_builder:
    uri: "configs/env/mettagrid/maps/multiagent/wallblocker.map"
