# see reference_design.yaml for explanation of components
_target_: agent.metta_agent.MettaAgent

policy_selector:
  uri: null
  type: top
  range: 0
  metric: final.score
  generation: null

observations:
  obs_key: grid_obs
  track_last_action: ${env.track_last_action}
  
clip_range: 0
effective_rank_interval: 10
l2_init_weight_update_interval: 0

components:
#necessary source layers: _obs_, _core_
#necessary output layers: _action_param_, _value_
  _obs_: 
    _target_: agent.lib.obs_shaper.ObsShaper
    input_source: null

  obs_normalizer:
    _target_: agent.lib.observation_normalizer.ObservationNormalizer
    input_source: _obs_
# change names etc.
  last_24_channels:
    _target_: agent.lib.merge_layer.ConcatMergeLayer
# change this to input_sources:
    input_source:
      - source_name: obs_normalizer
        slice: [0, 28]  
        dim: 1          

# change names etc.
  cnn1:
    _target_: agent.lib.nn_layer_library.Conv2d
    input_source: last_24_channels
    nn_params:
      out_channels: 64
      kernel_size: 5
      stride: 3

  cnn2:
    _target_: agent.lib.nn_layer_library.Conv2d
    input_source: cnn1
    nn_params:
      out_channels: 64
      kernel_size: 3
      stride: 1

  obs_flattener:
    _target_: agent.lib.nn_layer_library.Flatten
    input_source: cnn2

  fc1:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: obs_flattener
    nn_params:
      out_features: 128

  encoded_obs:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: fc1
    nn_params:
      out_features: 128

# ------------------------------------------------------------
  # change names etc.
  first_14_channels:
    _target_: agent.lib.merge_layer.ConcatMergeLayer
    input_source:
      - source_name: obs_normalizer
        slice: [0, 28]  # extract the first 14 channels
        dim: 1          # operates on the channel dimension
  
  # Extract the center row (height = 11 → 1)
  center_row:
    _target_: agent.lib.merge_layer.ConcatMergeLayer
    input_source:
      - source_name: first_14_channels
        slice: [5, 6]   # extract the center row (row index 5)
        dim: 2          # operates on the height dimension

  # Extract the center pixel from the center row (width = 11 → 1)
  center_pixel:
    _target_: agent.lib.merge_layer.ConcatMergeLayer
    input_source:
      - source_name: center_row
        slice: [5, 6]   # extract the center column (column index 5)
        dim: 3          # operates on the width dimension

  # Flatten (batch, channels, 1, 1) -> (batch, channels)
  center_pixel_flatten:
    _target_: agent.lib.nn_layer_library.Flatten
    input_source: center_pixel

  center_linear:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: center_pixel_flatten
    nn_params:
      out_features: 128

  self_info_encoded_obs_merger:
    _target_: agent.lib.merge_layer.ConcatMergeLayer
    input_source:
      - source_name: center_linear
      - source_name: encoded_obs

# ------------------------------------------------------------

  _core_:
    _target_: agent.lib.lstm.LSTM
    input_source: self_info_encoded_obs_merger
    output_size: 128
    nn_params:
      num_layers: 2
      
  critic_1:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: _core_
    nn_params:
      out_features: 1024
    nonlinearity: nn.Tanh
    effective_rank: true

  _value_:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: critic_1
    nn_params:
      out_features: 1
    nonlinearity: null

  actor_1:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: _core_
    nn_params:
      out_features: 512
    effective_rank: true

  _action_type_embeds_:
    _target_: agent.lib.nn_layer_library.Embedding
    input_source: null
    nn_params:
      num_embeddings: 50
      embedding_dim: 64

  _action_type_:
    _target_: agent.lib.action.ActionType
    input_source: 
      - source_name: actor_1
      - source_name: _action_type_embeds_
    nonlinearity: null

  _action_param_embeds_:
    _target_: agent.lib.action.ActionHash
    input_source: null
    embedding_dim: 4

  _action_param_:
    _target_: agent.lib.action.ActionParam
    input_source: 
      - source_name: actor_1
      - source_name: _action_param_embeds_
    nonlinearity: null