_target_: agent.metta_agent.MettaAgent

observation_encoder:
  _target_: agent.simple_encoder.SimpleConvAgent
  cnn_channels: 64
  obs_key: grid_obs
  normalize_features: true
  auto_normalize: false
  track_last_action: ${env.track_last_action}
  kinship: ${env.game.kinship}
  # path: _agent._encoder

fc:
  layers: 2
  output_dim: 128
  # l2_norm_scale: [0.1, 0, 1]


decoder:
  _target_: agent.decoder.Decoder

core:
  rnn_type: gru
  rnn_num_layers: 1
  rnn_size: 128

policy_selector:
  uri: null
  type: top
  range: 0
  metric: final.score
  generation: null

critic:
  path: _agent._critic_linear
  hidden_sizes: [512] # Set to [] for no hidden layer
  l2_norm_scale: [1, 0]

actor:
  path: atn_type
  hidden_sizes: [512] # Set to [] for no hidden layer
  l2_norm_scale: [0, 0, 1] # must be the same num of layers. include 0 for nonlinear layers.
  clipping_scale: [0, 0, 0.5] # must be the same num of layers. include 0 for nonlinear layers.
  # l2_init_scale: [0, 0, 0] # must be the same num of layers. include 0 for nonlinear layers.


