_target_: agent.metta_agent.MettaAgent

observation_encoder:
  _target_: agent.simple_encoder.SimpleConvAgent
  cnn_channels: 64
  obs_key: grid_obs
  normalize_features: true
  auto_normalize: false
  track_last_action: ${env.track_last_action}
  kinship: ${env.game.kinship}

  fc:
    layers: 1
    output_dim: 128

decoder:
  _target_: agent.decoder.Decoder

core:
  rnn_type: gru
  rnn_num_layers: 1
  rnn_size: 128

policy_selector:
  uri: null
  type: top
  range: 0
  metric: final.score
  generation: null

# critic:
#   hidden_sizes: [] # Set to [] for no hidden layer

critic:
  _target_: agent.components.Composer

  layers:
    - name: critic_1
      input: agent._decoder
      output: 512
      clip_scale: 0.1

    - name: critic_2
      layer_type: Dropout
      dropout_prob: 0.2

    - name: critic_3
      output: 128

    - name: critic_4
      output: 1

actor:
  hidden_sizes: [] # Set to [] for no hidden layer

components:
  - name: observation_encoder_1
    input: obs

  - name: observation_encoder_2

  - name: _encoded_obs_
    input: observation_encoder_2
    output: 128

  - name: _recurrent_
    output: 128

  - name: critic_1
    input: recurrent
    output: 512

  - name: critic_2
    input: critic_1
    output: 128

  - name: critic_3
    input: [actor_2, critic_2]
    output: 128

  - name: _value_
    output: 1

  - name: actor_1
    input: recurrent
    output: 512

  - name: actor_2

## test this but comment out critic_3
#   - name: actor_2
#     input: [actor_1, critic_1]
#     output: 128

  - name: _atn_param_
    output: 20


production_components:
  - name: obs_encoder
  # -- I need to wrap this --
    _target_: agent.simple_encoder.SimpleConvAgent
    cnn_channels: 64
    obs_key: grid_obs
    normalize_features: true
    auto_normalize: false
    track_last_action: ${env.track_last_action}
    kinship: ${env.game.kinship}

  - name: custom_module_1
    _target_: agent.components.CustomModule
    input: _decoder
    output: 512


  # critic:
  # _target_: agent.components.Composer
  # # access any layer of another net
  # # access combos of layers
  # input: '_decoder' # mandatory
  # output: 1 # mandatory
  # layers:
  #   - _target_: agent.components.Layer
  #     name: critic_1
  #     output: 512
  #     clip_scale: 0.1

  #   - _target_: agent.components.Layer
  #     name: critic_2
  #     type: nn.ReLU

  #   - _target_: agent.components.Layer
  #     name: critic_3


actor_simple_example:

  layers:
    - name: actor_1
      input: _decoder
      output: 512

    - name: atn_param

# ===============================

actor_complex_example:

  layers:
    - name: actor_1
      input: _decoder
      output: 512
      clip_scale: 0.1
      nonlinearity: Tanh

    - name: actor_2
      layer_type: Dropout
      dropout_prob: 0.2
    # this branches out!
    - name: actor_3
      input: actor_2
      output: 128

    - name: atn_type
      input: [actor_3, _encoder_out] # skip connection
      nonlinearity: None # need to specify output of this net :(

    - name: actor_4
      input: actor_2
      output: 256

    - name: atn_param
      input: actor_4
      nonlinearity: Softmax # we do our own nonlinearity if we choose
