_target_: agent.metta_agent.MettaAgent

observation_encoder:
  _target_: agent.simple_encoder.SimpleConvAgent
  cnn_channels: 64
  obs_key: grid_obs
  normalize_features: true
  auto_normalize: false
  track_last_action: ${env.track_last_action}
  kinship: ${env.game.kinship}

  fc:
    layers: 1
    output_dim: 128

decoder:
  _target_: agent.decoder.Decoder

core:
  rnn_type: gru
  rnn_num_layers: 1
  rnn_size: 128

policy_selector:
  uri: null
  type: top
  range: 0
  metric: final.score
  generation: null

# critic:
#   hidden_sizes: [] # Set to [] for no hidden layer

critic:
  _target_: agent.components.Composer
  # access any layer of another net
  # access combos of layers
  input: '_decoder' # mandatory
  output: 1 # mandatory
  layers:
    - name: critic_1
      output: 512
      clip_scale: 0.1

    - name: critic_2
      type: nn.ReLU

    - name: critic_3
      type: nn.Dropout
      dropout_prob: 0.2

    - name: critic_4
      type: nn.Linear

actor:
  hidden_sizes: [] # Set to [] for no hidden layer


  # critic:
  # _target_: agent.components.Composer
  # # access any layer of another net
  # # access combos of layers
  # input: '_decoder' # mandatory
  # output: 1 # mandatory
  # layers:
  #   - _target_: agent.components.Layer
  #     name: critic_1
  #     output: 512
  #     clip_scale: 0.1

  #   - _target_: agent.components.Layer
  #     name: critic_2
  #     type: nn.ReLU

  #   - _target_: agent.components.Layer
  #     name: critic_3


