_target_: agent.metta_agent.MettaAgent

policy_selector:
  uri: null
  type: top
  range: 0
  metric: final.score
  generation: null
  
observations:
  obs_key: grid_obs
  normalize_features: true
  auto_normalize: false
  track_last_action: ${env.track_last_action}
  # kinship: ${env.game.kinship}
  
clip_range: 3.0
effective_rank_interval: 10

components:
#necessary sources: _obs_, _core_
#necessary outputs: _encoded_obs_, _action_param_, _value_
  _obs_: 
    _target_: agent.lib.obs_shaper.ObsShaper
    input_source: null

  obs_normalizer:
    _target_: agent.lib.observation_normalizer.ObservationNormalizer
    input_source: _obs_

  cnn1:
    _target_: agent.lib.nn_layer_library.Conv2d
    input_source: obs_normalizer
    output_size: 64
    nn_params:
      kernel_size: 5
      stride: 3

  cnn2:
    _target_: agent.lib.nn_layer_library.Conv2d
    input_source: cnn1
    output_size: 64
    nn_params:
      kernel_size: 3
      stride: 1

  obs_flattener:
    _target_: agent.lib.nn_layer_library.Flatten
    input_source: cnn2

  fc1:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: obs_flattener
    output_size: 128

  _encoded_obs_:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: fc1
    output_size: 128

  _core_:
    _target_: agent.lib.nn_layer_library.LSTM
    input_source: _encoded_obs_
    output_size: 128
    nn_params:
      num_layers: 1
      
  critic_1:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: _core_
    output_size: 1024

  _value_:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: critic_1
    output_size: 1
    nonlinearity: None

  actor_1:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: _core_
    output_size: 512

  _action_param_:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: actor_1
    output_size: 20
    nonlinearity: None
