_target_: agent.metta_agent.MettaAgent

policy_selector:
  uri: null
  type: top
  range: 0
  metric: final.score
  generation: null


observation_encoder:
  _target_: agent.simple_encoder.SimpleConvAgent
  cnn_channels: 64
  obs_key: grid_obs
  normalize_features: true
  auto_normalize: false
  track_last_action: ${env.track_last_action}
  kinship: ${env.game.kinship}

  fc:
    layers: 1
    output_dim: 128

core:
  rnn_type: gru
  rnn_num_layers: 1
  rnn_size: 128

decoder:
  _target_: agent.components.Decoder


actor:
  - _target_: agent.components.Stack
    skip: true
    nonlinearity: nn.ReLU

    layers:
      - _target_: agent.components.LinearLayer
        output_size: 128
        l2_norm_scale: 0
        l2_init_scale: 0
        clip_scale: 0
      - _target_: agent.components.LinearLayer
        output_size: 128
        l2_norm_scale: 0
        l2_init_scale: 0
        clip_scale: 0
      - _target_: agent.components.LinearLayer
        output_size: ???
        l2_norm_scale: 0
        l2_init_scale: 0
        clip_scale: 0

critic:
  - _target_: agent.components.MultiStack
    template:
      _target_: agent.components.LinearLayer
      output_size: 128
      l2_norm_scale: 0
      l2_init_scale: 0
      clip_scale: 0
    repeat: 3


