_target_: agent.metta_agent.MettaAgent

policy_selector:
  uri: null
  type: top
  range: 0
  metric: final.score
  generation: null
  
observations:
  obs_key: grid_obs
  normalize_features: true
  auto_normalize: false
  track_last_action: ${env.track_last_action}
  kinship: ${env.game.kinship}

interface:
  input:
    obs: observation_encoder_1
    core_output: _core_

  output:
    encoded_obs: observation_encoder_1
    value: critic_3
    action_param: actor_2

components:

  obs_helper: 
    input_source: _obs_
    layer_type: Identity

  # obs_normalizer:
    ###

  # feature_normalizer:
    ###

  obs_encoder_1:
    _target_: agent.MettaLayer
    # input_source: obs_normalizer
    input_source: obs_helper
    output_size: 64 # number of channels
    layer_type: Conv2d
    kernel_size: 5
    stride: 3

  obs_encoder_2:
    _target_: agent.MettaLayer
    input_source: obs_encoder_1
    output_size: 64 # number of channels
    layer_type: Conv2d
    kernel_size: 3
    stride: 1

  obs_flattener:
    _target_: agent.MettaLayer
    input_source: obs_encoder_2
    layer_type: Flatten

  _encoded_obs_:
    _target_: agent.MettaLayer
    input_source: obs_flattener
    output_size: 128

  core_helper:
    _target_: agent.MettaLayer
    rnn_type: gru
    rnn_num_layers: 1
    rnn_size: 128
    input_source: _core_
    output_size: 128
    layer_type: Identity

  critic_1:
    _target_: agent.MettaLayer
    input_source: core_helper
    output_size: 512
    layer_type: Linear

  critic_2:
    _target_: agent.MettaLayer
    input_source: critic_1
    output_size: 128

  critic_3:
    _target_: agent.MettaLayer
    input_source: [actor_2, critic_2]
    output_size: 128

  # value:
  #   _target_: agent.nn.Linear
  #   input: critic_3
  #   output: 1

  actor_1:
    _target_: agent.MettaLayer
    input_source: core_helper
    output_size: 512

  actor_2:
    _target_: agent.MettaLayer
    input_source: actor_1
    output_size: 512

  _value_:
    _target_: agent.MettaLayer
    input_source: actor_2
    output_size: 1

# # test this but comment out critic_3
#   - name: actor_2
#     input: [actor_1, critic_1]
#     output: 128

  _atn_param_:
    _target_: agent.MettaLayer
    input_source: actor_2
    output_size: 20