defaults:
  - /env/mettagrid/mettagrid@
  - _self_


game:
  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 20
    border_width: 6

    room:
      _target_: mettagrid.config.room.random.Random
      width: ${sampling:10,25,20}
      height: ${sampling:10,25,20}
      border_width: 0

      agents: 1

      objects:
        # mine.red: 1
        # generator.red: 1
        # mine.blue: 1
        # generator.blue: 1
        # mine.green: 1
        generator.green: 12
        altar: 12
        block: 1
        wall: 1

  num_agents: 20
  max_steps: 1000

  agent:
    max_inventory: ${sampling:0, 100, 50}
    freeze_duration: ${sampling:0, 200, 10}
    hp: 10
    mortal: False
    rewards:
      # action_failure_penalty: 0.00001
      action_failure_penalty: 0
      ore.red: 0.001
      ore.blue: 0.001
      ore.green: 0.001
      battery.red: 0.001
      battery.blue: 0.001
      battery.green: 0.001
      battery_max: 10
      heart: 1
      heart_max: 1000


  objects:
    altar:
      hp: 30
      input_battery.green: 1
      output_heart: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 255
      initial_items: 0

    # mine.red:
    #   hp: 30
    #   output_ore.red: 1
    #   color: 0
    #   max_output: 5
    #   conversion_ticks: 1
    #   cooldown: 255
    #   initial_items: 1

    # mine.blue:
    #   hp: 30
    #   color: 1
    #   input_battery.red: 1
    #   output_ore.blue: 1
    #   max_output: 5
    #   conversion_ticks: 1
    #   cooldown: 255
    #   initial_items: 1

    # mine.green:
    #   hp: 30
    #   input_battery.blue: 1
    #   output_ore.green: 1
    #   color: 2
    #   max_output: 5
    #   conversion_ticks: 1
    #   cooldown: 255
    #   initial_items: 1

    # generator.red:
    #   hp: 30
    #   input_ore.red: 1
    #   output_battery.red: 1
    #   color: 0
    #   max_output: 5
    #   conversion_ticks: 1
    #   cooldown: 255
    #   initial_items: 0

    # generator.blue:
    #   hp: 30
    #   input_ore.blue: 1
    #   output_battery.blue: 1
    #   color: 1
    #   max_output: 5
    #   conversion_ticks: 1
    #   cooldown: 255
    #   initial_items: 0

    generator.green:
      hp: 30
      # input_ore.green: 1
      output_battery.green: 1
      color: 2
      max_output: 5
      conversion_ticks: 1
      cooldown: 255
      initial_items: 0