defaults:
  - /env/mettagrid/mettagrid/object_use/training/defaults
  - _self_


game:
  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom

    room:
      objects:
        generator.green: ${sampling:1,10, 5}
        generator.blue: ${sampling:1,10, 5}
        generator.red: ${sampling:1,10, 5}
        altar: ${sampling:1,10, 5}
        mine.green: ${sampling:1,10, 5}
        mine.blue: ${sampling:1,10, 5}
  objects:
    altar:
      input_battery.green: 1
      output_heart: 1
    generator.green:
      input_ore.green: 1
      output_battery.green: 1
    mine.green:
      input_battery.blue: 1
      output_ore.green: 1
    generator.blue:
      input_ore.blue: 1
      output_battery.blue: 1
