defaults:
  - mettagrid
  - game/map_builder: extended_sequence
  - _self_

game:
  num_agents: 24


objects:
  altar:
    hp: 30
    input_battery: 3
    output_heart: 1
    max_output: 5
    conversion_ticks: 1
    cooldown: ${sampling:1, 20, 10}
    initial_items: 0

  mine.red:
    hp: 30
    output_ore.red: 1
    color: 0
    max_output: 5
    conversion_ticks: 1
    cooldown: ${sampling:0, 100, 50}
    initial_items: 1

  mine.blue:
    hp: 30
    color: 1
    output_ore.blue: 1
    max_output: 5
    conversion_ticks: 1
    cooldown: ${sampling:0, 100, 50}
    initial_items: 1

  mine.green:
    hp: 30
    output_ore.green: 1
    color: 2
    max_output: 5
    conversion_ticks: 1
    cooldown: ${sampling:0, 100, 50}
    initial_items: 1

  generator.red:
    hp: 30
    input_ore.red: 1
    output_battery: 1
    color: 0
    max_output: 5
    conversion_ticks: 1
    cooldown: ${sampling:0, 50, 25}
    initial_items: 0

  generator.blue:
    hp: 30
    input_ore.blue: 1
    output_battery: 1
    color: 1
    max_output: 5
    conversion_ticks: 1
    cooldown: ${sampling:0, 50, 25}
    initial_items: 0

  generator.green:
    hp: 30
    input_ore.green: 1
    output_battery: 1
    color: 2
    max_output: 5
    conversion_ticks: 1
    cooldown: ${sampling:0, 50, 25}
    initial_items: 0
