_target_: metta.env.mettagrid_env_set.MettaGridEnvSet

num_agents: 20
sampling: 1


envs:
  - /env/mettagrid/object_use/training/extended_sequence0
  - /env/mettagrid/object_use/training/extended_sequence1
  - /env/mettagrid/object_use/training/extended_sequence2
  - /env/mettagrid/object_use/training/extended_sequence3
  - /env/mettagrid/object_use/training/extended_sequence4
  - /env/mettagrid/object_use/training/extended_sequence5
  - /env/mettagrid/object_use/training/extended_sequence6

increment_reward_thresholds: 
 - 10
 - 10
 - 10
 - 10
 - 10
 - 10
 - 10


