defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 4
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.room.terrain_from_numpy.TerrainFromNumpy
      border_width: ${sampling:1,6,3}
      agents: 1
      objects:
        altar: ${sampling:1,5,1}
        generator.red: ${sampling:1,10,1}
        mine.red: ${sampling:1,10,1}
  objects:
      altar:
        initial_items: ${choose:0,1}
        cooldown: ${sampling:1, 20, 10}

      generator.red:
        initial_items: ${choose:0,1}
        cooldown: ${sampling:5, 20, 10}

      generator.blue:
        cooldown: ${sampling:3, 20, 10}

      generator.green:
        cooldown: ${sampling:3, 20, 10}

      mine.red:
        cooldown: ${sampling:5, 20, 10}

      mine.blue:
        cooldown: ${sampling:5, 20, 10}

      mine.green:
        cooldown: ${sampling:5, 20, 10}
