defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

game:
  num_agents: 20

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 1
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.box_world.BoxWorld
      width:  120
      height: 120
      border_width: 2

      # optional size tweaks
      short_range: [6, 10]
      elong_range: [6, 10]

      agents: 20   # handled globally

  objects:
    altar:
      cooldown: 255

  actions:
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false
