defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

game:
  num_agents: 20

  map_builder:
    _target_: mettagrid.config.room.cubicle_world_uniform.CubicleUniformWorld

    # Arena dimensions sampled each episode
    width_range:  [120, 320]
    height_range: [120, 320]

    # Cubicle interior dimensions (gap between walls)
    gap_range: [4, 14]

    altars_count: 50
    agents: 20

  objects:
    altar:
      cooldown: 100