defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

game:
  num_agents: 20

  map_builder:
    _target_: mettagrid.config.room.empty_world.EmptyWorld

    # Arena dimensions (sampled per episode)
    width_range:  [60, 130]
    height_range: [60, 130]

    # How many altars to scatter each episode
    altars_count_range: [14, 40]

    agents: 20  # passed through to builder

  objects:
    altar:
      cooldown: 100