defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

game:
  num_agents: 20

  map_builder:
    _target_: mettagrid.config.room.giant_maze_world.GiantMazeWorld

    width:  250
    height: 250

    # corridors 2‑6 tiles wide, walls 1‑5 tiles thick (sampled every episode)
    corridor_range: [2, 6]
    wall_range:     [1, 5]

    altars_count: 75
    border_width: 2
    agents: 20

  objects:
    altar:
      cooldown: 100