defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

game:
  num_agents: 4         # total across the whole map

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4

    room:
      _target_: mettagrid.config.room.lattice_world.LatticeWorld
      num_agents: 1

  objects:
    altar:
      cooldown: 255

  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    put_items:
      enabled: true
    get_items:
      enabled: true
    attack:
      enabled: true  
    swap:
      enabled: true
    change_color:
      enabled: true