defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

game:
  num_agents: 20

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 1
    border_width: 6

    room:
      _target_: mettagrid.config.room.memory_box_world.MemoryBoxWorld
      width:  140
      height: 140
      border_width: 2

      # customise if desired
      size_range: [9, 14]      # interior side lengths
      corridor_range: [6, 10]  # corridor walls sampled per box

      agents: 20

  objects:
    altar:
      cooldown: 255

  
  actions:
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false
    put_items:
      enabled: false