defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

game:
  num_agents: 4

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.memory_box_world.MemoryBoxWorld
      width:  140
      height: 140
      border_width: 2

      # customise if desired
      size_range: [9, 14]      # interior side lengths
      corridor_range: [6, 10]  # corridor walls sampled per box

      agents: 1

  objects:
    altar:
      cooldown: 255
