_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  /env/mettagrid/navigation/training/terrain_from_numpy_resets: 0.2
  /env/mettagrid/navigation/training/varied_terrain_resets: 0.1
  /env/mettagrid/navigation/training/varied_terrain: 0.2
  /env/mettagrid/navigation/training/terrain_from_numpy: 0.2
  /env/mettagrid/navigation/training/terrain_from_numpy_with_generators: 0.1
  /env/mettagrid/navigation/training/cylinder_world: 0.2
