_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/navigation/training/terrain_from_numpy
  - /env/mettagrid/navigation/training/varied_terrain
  - /env/mettagrid/navigation/training/cylinder_world
  - /env/mettagrid/navigation/training/labyrinth_world
  - /env/mettagrid/navigation/training/hex_world
  - /env/mettagrid/navigation/training/giant_maze_world_varied
  - /env/mettagrid/navigation/training/cubicle_world
