_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 20

game:
  num_agents: ${..num_agents}

envs:
  # - /env/mettagrid/navigation/training/terrain_from_numpy
  # - /env/mettagrid/navigation/training/varied_terrain
  # - /env/mettagrid/navigation/training/terrain_from_numpy
  - /env/mettagrid/navigation/training/cylinder_world
  - /env/mettagrid/navigation/training/labyrinth_world
  - /env/mettagrid/navigation/training/cubicle_world
  - /env/mettagrid/navigation/training/memory_box_world
  - /env/mettagrid/navigation/training/giant_maze_world
  - /env/mettagrid/navigation/training/giant_maze_world_varied





probabilities:
  - 0.15
  - 0.20
  - 0.20
  - 0.20
  - 0.1
  - 0.15
