_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

sampling: 1

envs:
  /env/mettagrid/navigation/evals/memory_easy: 0.3
  /env/mettagrid/navigation/evals/memory_medium: 0.4
  /env/mettagrid/navigation/evals/memory_hard: 0.3
