_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  /env/mettagrid/navigation/training/terrain_from_numpy: 0.1
  /env/mettagrid/navigation/training/varied_terrain: 0.1
  /env/mettagrid/navigation/training/empty_world: 0.2
  /env/mettagrid/navigation/training/cubicle_world_uniform: 0.3
  /env/mettagrid/navigation/training/hex_world: 0.15
  /env/mettagrid/navigation/training/square_world: 0.15