_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/navigation/training/terrain_from_numpy
  - /env/mettagrid/navigation/training/varied_terrain
  - /env/mettagrid/navigation/training/terrain_from_numpy_with_generators


probabilities:
  - 0.3
  - 0.4
  - 0.3
