_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/navigation/training/terrain_from_numpy_resets
  - /env/mettagrid/navigation/training/varied_terrain_resets
  - /env/mettagrid/navigation/training/lattice_world


probabilities:
  - 0.35
  - 0.35
  - 0.3
