_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  /env/mettagrid/navigation/training/terrain_from_numpy: 0.05
  /env/mettagrid/navigation/training/varied_terrain: 0.05
  /env/mettagrid/navigation/training/empty_world: 0.9
 

