_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  /env/mettagrid/navigation/training/terrain_from_numpy: 0.3
  /env/mettagrid/navigation/training/varied_terrain: 0.4
  /env/mettagrid/navigation/training/terrain_from_numpy_with_generators: 0.3
