_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  /env/mettagrid/navigation/training/terrain_from_numpy: 0.3
  /env/mettagrid/navigation/training/varied_terrain: 0.3
  /env/mettagrid/navigation/training/cylinder_world: 0.1
  /env/mettagrid/navigation/training/labyrinth_world: 0.05
  /env/mettagrid/navigation/training/hex_world: 0.05
  /env/mettagrid/navigation/training/giant_maze_world_varied: 0.15
  /env/mettagrid/navigation/training/cubicle_world: 0.05
