defaults:
  - /env/mettagrid/mettagrid@
  - _self_

curriculum:
  _target_: mettagrid.curriculum.curriculum.MultiEnvCurriculum
  tasks:
    /env/mettagrid/navigation/training/terrain_from_numpy: 0.5
    /env/mettagrid/navigation/training/varied_terrain: 0.4
    /env/mettagrid/navigation/training/cylinder_world: 0.1

game:
  num_agents: 4

