_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/navigation/training/terrain_from_numpy
  - /env/mettagrid/navigation/training/varied_terrain_all_sparse
  - /env/mettagrid/navigation/training/varied_terrain_sparse_altars_dense_objects
  - /env/mettagrid/navigation/training/varied_terrain_balanced
  - /env/mettagrid/navigation/training/varied_terrain_maze
