defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

game:
  num_agents: 4

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.square_world.SquareWorld

      # Overall arena size (sampled each episode)
      width_range:  [60, 160]
      height_range: [60, 160]

      # Homogeneous square size and corridor width
      square_size_range: [3, 7]
      gap_range:         [3, 8]

      altars_count: 40
      agents: 1

  objects:
    altar:
      cooldown: 100
