defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1
game:
  num_agents: 4  #how many agents are in the map x2

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${..num_agents}
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.terrain_from_numpy.TerrainFromNumpy
      border_width: 1
      dir: "terrain_maps_nohearts"
      num_agents: 1
