defaults:
  - mettagrid
  - _self_

game:
  num_agents: 4
  map_builder:
    room:
      _target_: mettagrid.config.room.terrain_from_numpy.TerrainFromNumpy
      border_width: 0
      agents: 4
      objects:
        altar: ${sampling:15,50,1}
