defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

sampling: 1

game: 
  max_steps: 1000
  num_agents: 4
  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
      width: 100
      height: 100
      border_width: ${sampling:1,6,3}
      agents: 1
      style: all-dense # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}

