name: 'Setup Python and uv'
description: 'Set up Python and uv with caching and virtual environment'

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: '0.7.3'
        enable-cache: true
        cache-dependency-glob: "requirements*.txt"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Create and activate virtual environment
      shell: bash
      run: |
        python -m venv .venv
        echo "Created virtual environment at .venv"
        # Add .venv/bin to PATH for subsequent steps
        echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

    - name: Install pip requirements into virtual environment
      shell: bash
      run: |
        # Use uv to install dependencies into the virtual environment
        uv pip install -r requirements.txt --python "$(pwd)/.venv/bin/python"
        echo "Installed requirements into .venv"