
num_envs_per_worker: ???
num_workers: ???
resume: true

total_timesteps: 50_000_000_000

learning_rate: 0.001474905225757153
gamma: 0.985659693849252
gae_lambda: 0.9404377415848161
clip_coef: 0.014131532393213114
vf_coef: 0.7582342079125987
vf_clip_coef: 0.261408122998913
max_grad_norm: 1.4960777759552002
ent_coef: 0.003545244069005398

norm_adv: true
clip_vloss: true
target_kl: null
anneal_lr: false

env_batch_size: null
zero_copy: true
verbose: true

checkpoint_interval: 60
wandb_checkpoint_interval: 300

batch_size: 262144
minibatch_size: 8192
bptt_horizon: 32
update_epochs: 3

cpu_offload: false
compile: false
compile_mode: reduce-overhead

forward_pass_minibatch_target_size: 2048
async_factor: 2

stats:
  overview:
    episode/reward.mean: episode_reward
  step: train/agent_steps

