
num_envs_per_worker: ???
num_workers: ???
resume: true

total_timesteps: 50_000_000_000

clip_coef: 0.011102333784435113
ent_coef: 0.01376980586465873
gae_lambda: 0.9776227170639571
gamma: 0.8567482546637853
learning_rate: 0.002064722899262613
max_grad_norm: 0.8660179376602173
vf_clip_coef: 0.26475190539131727
vf_coef: 0.3403069830175013

norm_adv: True
clip_vloss: True
target_kl: null
anneal_lr: false

env_batch_size: null
zero_copy: true
verbose: true

checkpoint_interval: 60
wandb_checkpoint_interval: 300

batch_size: 262144
minibatch_size: 32768
bptt_horizon: 16
update_epochs: 1

cpu_offload: false
compile: false
compile_mode: reduce-overhead

forward_pass_minibatch_target_size: 4096
async_factor: 2

stats:
  overview:
    episode/reward.mean: episode_reward
  step: train/agent_steps


