resources:
  cloud: aws
  region: us-west-2
  instance_type: p3.2xlarge
  use_spot: true

setup: |
  # Install dependencies
  pip install -r requirements.txt

run: |
  # Your training command here
  python train.py

file_mounts:
  ~/project: .
