resources:
  cloud: aws
  region: us-east-1
  instance_type: g6.4xlarge
  use_spot: true
  accelerators: {L4: 1}  # 4 GPUs per node
  image_id: 767406518141.dkr.ecr.us-east-1.amazonaws.com/metta:latest

setup: |
  # Install dependencies
  pip install -r requirements.txt
  ./devops/setup_build.sh

run: |
  source deactivate
  nvidia-smi

file_mounts:
  /mnt/efs/train_dir: train_dir

workdir: .

envs:
  SKYPILOT_DOCKER_USERNAME: AWS
  SKYPILOT_DOCKER_PASSWORD: SKYPILOT_DOCKER_PASSWORD
  SKYPILOT_DOCKER_SERVER: 767406518141.dkr.ecr.us-east-1.amazonaws.com
