# @package __global__

seed: null

defaults:
  - override /eval: eval_suite
  - override /env/mettagrid@env: cognitive_evals/cogeval_training_mini_simplified
  - override /agent: simple
  - override /sweep: fast
  - override /analyzer: analyzer

#policy_uri: wandb://run/daphne_training_e3b_cogeval_simplified_vast_e0.05_2
policy_uri: wandb://run/b.daphne.aws_train_cogeval_simplified_0.01_mb
#policy_uri: ${trained_policy_uri}

npc_policy_uri: null

trainer:
  evaluate_interval: 2
  use_e3b: true


eval:
  num_envs: 2
  num_episodes: 2
  max_time_s: 300
 # eval_db_uri: ${..eval_db_uri} #file://daphne/sweep_stats

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1
evaluate_interval: 1

sweep:
  metric: "action.use.altar.agent"

cmd: ???
run_id: 27
run: ${oc.env:USER}.local.${cmd}.${run_id}
trained_policy_uri: ./train_dir/${oc.env:USER}.local.train.${run_id}/checkpoints
