# @package __global__

seed: null

defaults:
  - override /env/mettagrid@env: cogeval_training_hard
  - override /agent: simple.medium
  - override /sweep: fast
# policy: wandb://run/b.daveey.train.maze.sm.dr.warm.0
# baselines: wandb://run/b.daveey.train.maze.sm.11x11.0

policy_uri: wandb://run/cogeval_training_mini_med
baseline_uri: wandb://run/mb.daveey.sm.nr

env:
  sampling: 1

  game:
    max_steps: 1000
    actions:
      jump:
        enabled: false
        cost: 3
      shield:
        enabled: false
        cost: 1
      transfer:
        enabled: false
        cost: 0
      attack:
        enabled: false
        cost: ${uniform:1, 100, 10}
      gift:
        enabled: false
        cost: 0
      swap:
        enabled: false
        cost: 0
      change_color:
        enabled: false
        cost: 0
trainer:
  evaluate_interval: 2

evaluator:
  policy:
    uri: ${...policy_uri}

  baselines:
    uri: ${...baseline_uri}

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1

sweep:
  metric: action.use

cmd: ???
run_id: 8
run: ${oc.env:USER}.local.${cmd}.${run_id}
trained_policy_uri: ./train_dir/${oc.env:USER}.local.train.${run_id}/checkpoints
