# @package __global__

seed: null

defaults:
  - override /eval: eval_suite
  - override /env/mettagrid@env: simple
  - override /agent: simple
  - override /sweep: fast
  - override /analyzer: analyzer

#policy_uri: wandb://run/cogeval_training_sweep_mini.r.9
#policy_uri: ./train_dir/daphne.local.train.14_pfs/checkpoints/model_0050.pt
#policy_uri: ${trained_policy_uri}

npc_policy_uri: null

 # eval_db_uri: ${..eval_db_uri} #file://daphne/sweep_stats

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1
evaluate_interval: 1

cmd: ???
run_id: 19
run: ${oc.env:USER}.local.${cmd}.${run_id}
trained_policy_uri: ./train_dir/${oc.env:USER}.local.train.${run_id}/checkpoints
