# @package __global__

seed: null

defaults:
  - override /env/mettagrid@env: cogeval_training
  - override /agent: simple
  - override /sweep: fast
# policy: wandb://run/b.daveey.train.maze.sm.dr.warm.0
# baselines: wandb://run/b.daveey.train.maze.sm.11x11.0

policy_uri: ${trained_policy_uri}
baseline_uri: wandb://run/mb.daveey.sm.nr

env:
  sampling: 1

  game:
    max_steps: 1000

trainer:
  evaluate_interval: 2

evaluator:
  policy:
    uri: ${...policy_uri}
  baselines:
    uri: ${...baseline_uri}

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1

sweep:
  metric: action.use

cmd: ???
run_id: 8
run: ${oc.env:USER}.local.${cmd}.${run_id}
trained_policy_uri: ./train_dir/${oc.env:USER}.local.train.${run_id}/checkpoints
