# @package __global__

defaults:
  - override /agent: simple
  - override /eval: simple
  - override /analyzer: policy_analyzer

trainer:
  env: /env/mettagrid/bases
  evaluate_interval: 200

# policy: wandb://run/b.daveey.train.maze.sm.dr.warm.0
# baselines: wandb://run/b.daveey.train.maze.sm.11x11.0

# policy_uri: wandb://run/b.daveey.sm.train.er.new.0
# policy_uri: wandb://run/daveey.ar.cards.1
# policy_uri: wandb://run/b.daveey.t.32.instant
policy_uri: wandb://run/cogeval_training_mini_simplified.r.0
# policy_uri:  wandb://run/b.daphne.colored_mines_meta_varied:v6
eval_db_uri: wandb://artifacts/georgemetalearning

analyzer:
  eval_stats_uri: ${run_dir}/eval_stats
  policy_uri: ${..policy_uri}

eval:
  num_envs: 10
  num_episodes: 16
  max_time_s: 600
  env: /env/mettagrid/cogeval_training_medium_simplified


  policy_uri: ${..policy_uri}
  # npc_policy_uri: ${..npc_policy_uri}
  eval_db_uri: ${..eval_db_uri} #file://daphne/sweep_stats

wandb:
  checkpoint_interval: 1

run_id: 13
run: ${oc.env:USER}.local.${run_id}
trained_policy_uri: ${run_dir}/checkpoints

sweep_params: "sweep/fast"
sweep_name: "${oc.env:USER}.local.sweep.${run_id}"
seed: null
