# @package __global__

defaults:
  - override /agent: simple
  - override /eval: eval


trainer:
  env: /env/mettagrid/colored_mines
  evaluate_interval: 2
  env_overrides:
    # sampling: 0.7
    game:
      max_steps: 1000

policy_uri: wandb://run/george_mtg_breakout_2.r.0


analyzer:
  eval_stats_uri: ${run_dir}/eval_stats
  analysis:
    metrics:
      - metric: episode_reward
      - metric: "*.get"

eval:
  num_envs: 2
  num_episodes: 2
  max_time_s: 600

  policy_uri: ${..policy_uri}
  # npc_policy_uri: ${..npc_policy_uri}
  # eval_db_uri: ${..eval_db_uri} #file://daphne/sweep_stats
  env: /env/mettagrid/colored_mines

wandb:
  checkpoint_interval: 1

run_id: 100
run: ${oc.env:USER}.local.${run_id}
trained_policy_uri: ${run_dir}/checkpoints

sweep_params: "sweep/fast"
sweep_name: "${oc.env:USER}.local.sweep.${run_id}"
seed: null
