# @package __global__

seed: null

defaults:
  - override /eval: cogeval_suite
  - override /env/mettagrid@env: cognitive_evals/corridor_maze
  - override /agent: simple
  - override /sweep: fast
  - override /analyzer: analyzer

#policy_uri: wandb://run/b.daphne.aws_train_cogeval_simplified_0.01_mb:v36
#eval_db_uri: wandb://artifacts/cogeval_mini_simplified2
#policy_uri: ./train_dir/daphne.local.train.14_pfs/checkpoints/model_0050.pt
#policy_uri: ${trained_policy_uri}
policy_uri: wandb://run/mettabox_cogeval_defaults_lowent_initialized0005:v100
# policy_uri: wandb://run/daphne_mettabox_train_cogeval_simplified_0.01_mb_easyv33
#policy_uri: wandb://run/b.daphne.aws_train_cogeval_defaults_0.005_v35
#ABOVE IS b.daphne.aws_train_cogeval_easy_simplified_pretrained
npc_policy_uri: null


eval:
  policy_uri: ${policy_uri}

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1
evaluate_interval: 1


cmd: ???
run_id: 41
run: ${oc.env:USER}.local.${cmd}.${run_id}
trained_policy_uri: ./train_dir/${oc.env:USER}.local.train.${run_id}/checkpoints

env:
  game:
    max_steps: 1000

    objects:
      altar:
        hp: 30
        cooldown: 1

      mine:
        hp: 30
        cooldown: 1

      generator:
        hp: 30
        cooldown: 1

      armory:
        hp: 30
        cooldown: 1

      lasery:
        hp: 30
        cooldown: 1

      lab:
        hp: 30
        cooldown: 1

      factory:
        hp: 30
        cooldown: 1

      temple:
        hp: 30
        cooldown: 1

      wall:
        hp: ${uniform:1, 20, 10}

    # actions:
    #   noop:
    #     enabled: true
    #   move:
    #     enabled: true
    #   rotate:
    #     enabled: true
    #   attack:
    #     enabled: false
    #   swap:
    #     enabled: false
    #   change_color:
    #     enabled: false
