# @package __global__

seed: null

defaults:
  - /eval: example
  - override /env/mettagrid@env: simple
  - override /agent: simple.medium
  - override /sweep: fast
  - override /analyzer: artifact_analyzer

policy_uri: ${trained_policy_uri}
npc_policy_uri: ${trained_policy_uri}

env:
  # sampling: 0.7
  game:
    max_steps: 1000

    map_builder:
      border_width: 0

trainer:
  evaluate_interval: 2

eval:
  num_envs: 10
  num_episodes: 10
  max_time_s: 600

  policy_uri: ${..policy_uri}
  npc_policy_uri: ${..npc_policy_uri}
  log_eval_artifact: true
  eval_artifact_name: daphne_eval #if not null, will log to wandb

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1
evaluate_interval: 1

sweep:
  metric: action.use

cmd: ???
run_id: 6
run: ${oc.env:USER}.local.${cmd}.${run_id}
trained_policy_uri: ./train_dir/${oc.env:USER}.local.train.${run_id}/checkpoints
