# @package __global__

defaults:
  - override /agent: simple
  - override /eval: cogeval_suite
  - override /analyzer: eval_analyzer

trainer:
  env: /env/mettagrid/bases
  evaluate_interval: 200
  env_overrides:
    # sampling: 0.7
    game:
      num_agents: 36
      max_steps: 1000

# policy: wandb://run/b.daveey.train.maze.sm.dr.warm.0
# baselines: wandb://run/b.daveey.train.maze.sm.11x11.0

# policy_uri: wandb://run/b.daveey.sm.train.er.new.0
# policy_uri: wandb://run/daveey.ar.cards.1
# policy_uri: wandb://run/b.daveey.t.32.instant
policy_uri:  wandb://run/b.georgedeane.colored_mines_constrained
# npc_policy_uri: ${trained_policy_uri}
eval_db_uri: wandb://artifacts/test_daveey_e3b

analyzer:
  eval_stats_uri: ${run_dir}/eval_stats
  policy_uri: ${..policy_uri}
  analysis:
    metrics:
      - metric: episode_reward

eval:
  num_envs: 128
  num_episodes: 128
  max_time_s: 600


  policy_uri: ${..policy_uri}
  # npc_policy_uri: ${..npc_policy_uri}
  eval_db_uri: ${..eval_db_uri} #file://daphne/sweep_stats
  env_overrides:
    # sampling: 0.7
    game:
      # num_agents: 360
      max_steps: 10

<<<<<<< HEAD
wandb:
  checkpoint_interval: 1

run_id: 13
=======
analyzer:
  eval_stats_uri: ${run_dir}/eval_stats
  analysis:
    metrics:
      - metric: episode_reward
      - metric: "*.get"

eval:
  num_envs: 2
  num_episodes: 2
  max_time_s: 600

  policy_uri: ${..policy_uri}
  # npc_policy_uri: ${..npc_policy_uri}
  # eval_db_uri: ${..eval_db_uri} #file://daphne/sweep_stats
  env: /env/mettagrid/colored_mines

wandb:
  checkpoint_interval: 1

run_id: 100
>>>>>>> 627c8e416f59236cd685c8667e05e8ba89018301
run: ${oc.env:USER}.local.${run_id}
trained_policy_uri: ${run_dir}/checkpoints

sweep_params: "sweep/fast"
sweep_name: "${oc.env:USER}.local.sweep.${run_id}"
seed: null
