# @package __global__

seed: null

defaults:
  - override /eval: cogeval_suite
  - override /env/mettagrid@env: cognitive_evals/cogeval_training_easy_simplified
  - override /agent: simple
  - override /sweep: fast
  - override /analyzer: analyzer

#policy_uri: wandb://run/b.daphne.aws_train_cogeval_simplified_0.01_mb:v36
#eval_db_uri: wandb://artifacts/cogeval_mini_simplified2
#policy_uri: ./train_dir/daphne.local.train.14_pfs/checkpoints/model_0050.pt
#policy_uri: ${trained_policy_uri}
policy_uri: wandb://run/b.daphne.aws_train_cogeval_defaults_0.005_v35
npc_policy_uri: null


eval:
  policy_uri: ${policy_uri}

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1
evaluate_interval: 1


cmd: ???
run_id: 41
run: ${oc.env:USER}.local.${cmd}.${run_id}
trained_policy_uri: ./train_dir/${oc.env:USER}.local.train.${run_id}/checkpoints
