# @package __global__

defaults:
  - _self_

trainer:
  # env: /env/mettagrid/multienv_mettagrid
  env: /env/mettagrid/navigation/training/multienv_with_cylinder
  env_overrides:
    game:
      max_steps: 13
  evaluate_interval: 200
  optimizer:
    type: muon

sim:
  env: /env/mettagrid/navigation/training/multienv_with_cylinder
  env_overrides:
    game:
      max_steps: 13


  # env_overrides:
  #   sampling: 0.7
  #   game:
  #     num_agents: 36
  #     max_steps: 1000

# policy: wandb://run/b.daveey.train.maze.sm.dr.warm.0
# baselines: wandb://run/b.daveey.train.maze.sm.11x11.0

# policy_uri: wandb://run/b.daveey.t.1.bl
# policy_uri: wandb://run/b.daveey.t.16.dr0

# policy_uri: wandb://run/b.daveey.t.4.lra.muon
policy_uri: wandb://run/b.daveey.t.1.lra.dr.muon
# policy_uri: /tmp/puffer_metta_serial.pt

npc_policy_uri: ${policy_uri}
# npc_policy_uri: wandb://run/b.daveey.t.16.dr0
# policy_uri: ${trained_policy_uri}
# npc_policy_uri: ${trained_policy_uri}
eval_db_uri: wandb://artifacts/daveey_eval_testing

analyzer:
  policy_uri: ${..policy_uri}
  eval_stats_uri: ${run_dir}/eval_stats
  analysis:
    metrics:
      - metric: episode_reward
      - metric: "heart.get"


wandb:
  checkpoint_interval: 1

run_id: 16
run: ${oc.env:USER}.local.${run_id}
trained_policy_uri: ${run_dir}/checkpoints

sweep_params: "sweep/fast"
sweep_name: "${oc.env:USER}.local.sweep.${run_id}"
seed: null
