# @package __global__

seed: null

defaults:
  - override /env/mettagrid@env: simple
  - override /agent: simple.medium
  - override /sweep: fast
  - override /eval: example
  - override /analyzer: analyzer


# policy: wandb://run/b.daveey.train.maze.sm.dr.warm.0
# baselines: wandb://run/b.daveey.train.maze.sm.11x11.0

policy_uri: wandb://run/b.daveey.sm.train.er.new.0
npc_policy_uri: null
eval_db_uri: wandb://artifacts/daphne_eval

env:
  game:
    max_steps: 100

trainer:
  evaluate_interval: 2

eval:
  policy_uri: ${..policy_uri}
  npc_policy_uri: ${..npc_policy_uri}
  #eval_db_uri: wandb://artifacts/daphne_eval
  eval_db_uri: ${..eval_db_uri}

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1

sweep:
  metric: agent.action.use.*


cmd: ???
run: ${oc.env:USER}.local.${cmd}.2
