# @package __global__

defaults:
  - override /sim: simple
  - override /agent: transformer
  - override /analyzer: eval_analyzer
  - override /trainer: transformer
  - _self_


device: cuda
# vectorization: multiprocessing
vectorization: serial

trainer:
  num_workers: 12
  async_factor: 1
  zero_copy: true
  env: /env/mettagrid/simple
  # evaluate_interval: 0
  profiler_interval_epochs: 0
  # replay_interval: 0
  # evaluate_interval: 0
  env_overrides:
    sampling: 0.7
    game:
      num_agents: 36
      max_steps: 1023 # 1024 - 1

analyzer:
  policy_uri: ${..policy_uri}
  view_type: latest
  analysis:
    metrics:
      - metric: episode_reward
      - metric: "heart.get"


sim:
  env: /env/mettagrid/puffer
  num_envs: 1
  num_episodes: 1
  max_time_s: 600

# wandb:
#   enabled: false
#   track: false

run_id: 76
run: ${oc.env:USER}.local.${run_id}
trained_policy_uri: ${run_dir}/checkpoints

sweep_params: "sweep/fast"
sweep_name: "${oc.env:USER}.local.sweep.${run_id}"
seed: null
