# @package __global__

seed: null

defaults:
  - override /eval: eval_suite
  - override /env/mettagrid@env: ascii/breakout
  - override /agent: simple
  - override /sweep: fast
  - override /analyzer: train_analyzer

policy_uri: ${trained_policy_uri}
# policy_uri: wandb://run/cogeval_training_mini_pretrained_ent0.02
#eval_db_uri: file://daphne/daphne_eval_stats

npc_policy_uri: null

env:
  # sampling: 0.7
  game:
    max_steps: 1000

    map_builder:
      border_width: 0
    actions:
      attack:
        enabled: false

trainer:
  evaluate_interval: 2

eval:
  num_envs: 10
  num_episodes: 10
  max_time_s: 600

  policy_uri: ${..policy_uri}
  npc_policy_uri: ${..npc_policy_uri}
  eval_db_uri: ${..eval_db_uri} #file://daphne/sweep_stats

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1
evaluate_interval: 1

cmd: ???
run_id: 24
run: ${oc.env:USER}.local.${cmd}.${run_id}
trained_policy_uri: ./train_dir/${oc.env:USER}.local.train.${run_id}/checkpoints
