# @package __global__

defaults:
  - _self_


# Basic config variables
run_id: 23
run: ${oc.env:USER}.local.${run_id}
data_dir: ./train_dir
run_dir: ${data_dir}/${run}
policy_uri: wandb://run/b.daphne.navigation_multiagent_24_rewardsharing_maxinv
trained_policy_uri: ${run_dir}/checkpoints
eval_db_uri: wandb://stats/evals_jack_testing_1

trainer:
  evaluate_interval: 100
  checkpoint_interval: 50

sim_job:
  simulation_suite:
    num_envs: 2
    num_episodes: 2
  policy_uris:
    - wandb://run/b.daphne.navigation
    - wandb://run/b.daphne.navigation2
    - wandb://run/b.daphne.navigation_multiagent_24_rewardsharing_maxinv
    - wandb://run/b.daphne.navigation_multiagent_24_norewardsharing_maxinv

analyzer:
#  output_path: s3://softmax-public/policydash/dashboard.html
  output_path: s3://softmax-public/users/jack/policydash/dashboard.html


sweep_name: ${oc.env:USER}.local.sweep.${run_id}
