# @package __global__

defaults:
  - override /agent: simple
  - override /eval: navigation
  - override /analyzer: eval_analyzer
  - _self_

trainer:
  env: /env/mettagrid/navigation/training/multienv
  evaluate_interval: 50
  checkpoint_interval: 50
  env_overrides:
    game:
      actions:
        attack:
          enabled: false
        put_items:
          enabled: false
        swap:
          enabled: false
        change_color:
          enabled: false

env:
  semi_compact_obs: true
  game:
    num_agents: 20
    max_steps: 2000

policy_uri: "wandb://run/jack.lattice.aws"
analyzer:
  policy_uri: ${..policy_uri}
  view_type: latest
  analysis:
    metrics:
      - metric: episode_reward
#  output_path: s3://softmax-public/policydash/dashboard.html
  output_path: s3://softmax-public/users/jack/policydash/dashboard.html

eval:
  env: /env/mettagrid/navigation/evals/navigation
  num_episodes: 1
  num_envs: 1
  policy_uri: ${..policy_uri}
  selector_type: latest
  eval_db_uri: wandb://artifacts/navigation_db
  max_time_s: 3
  policy_uris:
    - "wandb://run/jack.lattice.aws"

wandb:
  checkpoint_interval: 1

run_id: 18
run: ${oc.env:USER}.local.${run_id}
trained_policy_uri: ${run_dir}/checkpoints

sweep_params: "sweep/fast"
sweep_name: "${oc.env:USER}.local.sweep.${run_id}"
seed: null
