# @package __global__


# defaults:
#   - _self_

wandb:
  enabled: true
  track: true

trainer:
  env: /env/mettagrid/diversity/multi_left_or_right

run: 13-05-left-right-eval-bonus-on
policy_uri: wandb://run/left-right-multiroom-7
