# @package __global__


# defaults:
#   - _self_

# # policy_uri: wandb://run/b.daveey.t.8.rdr9.3

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1

# trainer:
#   replay_interval: 2

# run_id: left_right_test
# run: ${oc.env:USER}.local.${run_id}
# trained_policy_uri: ${run_dir}/checkpoints
# # sweep_name: "${oc.env:USER}.local.sweep.${run_id}"



run: left-right-multiroom
policy_uri: wandb://run/left_right_test_2

# trainer:
#   sim:
#     env: /env/mettagrid/navigation/training/terrain_from_numpy

