# @package __global__

defaults:
  - /sim/navigation_object-use
  - _self_

trainer:
  env: env/mettagrid/object_use/training/large_multienv
  initial_policy:
    uri: wandb://run/daphne_objectuse_allobjs_multienv:v94
  evaluate_interval: 100
  checkpoint_interval: 100

train_job:
  evals: /sim/navigation_object-use

run: mrazo_object-use_allobs_large-multienv_v01