# @package __global__

defaults:
  - _self_

trainer:
  env: env/mettagrid/object_use/generator/training/generator_varied_terrain.yaml
  # initial_policy:
  #   uri: wandb://run/MRM_test_mettabox
  evaluate_interval: 300

sim: /sim/navigation_generator

train_job:
  evals: ${sim}

sim_job:
  simulation_suite: ${sim}