# @package __global__

defaults:
  - _self_

trainer:
  env: env/mettagrid/object_use/training/large-small_multienv
  # initial_policy:
  #   uri: wandb://run/daphne_objectuse_allobjs_multienv:v94
  evaluate_interval: 100
  checkpoint_interval: 100

run: mrazo_object-use_allobs_large-small-multienv_v01