# @package __global__

defaults:
  - /sim/navigation_object-use@train_job.evals
  - _self_

trainer:
  env: env/mettagrid/object_use/training/large_multienv
  initial_policy:
    uri: wandb://run/daphne_objectuse_allobjs_multienv:v94
  evaluate_interval: 100

run: mrazo_object-use_allobs_large-multienv_v01