# @package __global__

seed: null

defaults:
  # - override /env/mettagrid@env: simple
  # - override /agent: non_robust_puffer
  - _self_

<<<<<<< HEAD
policy_uri: puffer://checkpoints/metta-wombo/model_019074.pt
npc_policy_uri: null

puffer:
  _target_: metta.agent.external.lstm_transformer.Recurrent
  hidden_size: 384 
  cnn_channels: 128
=======
policy_uri: puffer://checkpoints/metta-example/model_019074.pt
npc_policy_uri: null

agent:
  #policy_class: null
  policy_class: metta.agent.external.example.Recurrent
>>>>>>> 4b8e6eafd69122bacfa815bdd8678e43b5134d2a

trainer:
  checkpoint_interval: 10
  evaluate_interval: 10
    #env: /env/mettagrid/navigation/training/multienv
  initial_policy:
<<<<<<< HEAD
     uri: puffer://checkpoints/metta-wombo/model_019074.pt
=======
     uri: puffer://checkpoints/metta-example/model_019074.pt
>>>>>>> 4b8e6eafd69122bacfa815bdd8678e43b5134d2a
     #uri: puffer://checkpoints/metta-wombo/model_019074.pt

eval:
  policy_uri: ${..policy_uri}
  npc_policy_uri: ${..npc_policy_uri}
  #eval_db_uri: train_dir/richard.dummy.1/

run: ${oc.env:USER}.local.${run_id}
<<<<<<< HEAD
trained_policy_uri: puffer://checkpoints/metta-wombo/model_019074.pt
=======
trained_policy_uri: puffer://checkpoints/metta-example/model_019074.pt
>>>>>>> 4b8e6eafd69122bacfa815bdd8678e43b5134d2a
