# @package __global__

seed: null

defaults:
  # - override /env/mettagrid@env: simple
  # - override /agent: non_robust_puffer
  - _self_

    #policy_uri: puffer://puffer_checkpoints/metta-example/model_019074.pt
policy_uri: puffer://puffer_checkpoints/metta-wombo/model_019074.pt
npc_policy_uri: null

agent:
  policy_class: metta.agent.external.lstm_transformer.Recurrent

trainer:
  checkpoint_interval: 10
  evaluate_interval: 10
    #env: /env/mettagrid/navigation/training/multienv
  initial_policy:
    #uri: puffer://puffer_checkpoints/metta-example/model_019074.pt
    uri: puffer://puffer_checkpoints/metta-wombo/model_019074.pt

eval:
  policy_uri: ${..policy_uri}
  npc_policy_uri: ${..npc_policy_uri}
  #eval_db_uri: train_dir/richard.dummy.1/

run: ${oc.env:USER}.local.${run_id}
  #trained_policy_uri: puffer://puffer_checkpoints/metta-example/model_019074.pt
