defaults:
  - /env/mettagrid/multiagent/training/48/varied_terrain_dense@
  - _self_

sampling: 1

game:
  num_agents: 48

  reward_sharing:
    groups:
      team_1:
        team_1: 0.3
      team_2:
        team_2: 0.3
      team_3:
        team_3: 0.3
      team_4:
        team_4: 0.3
