_target_: metta.env.mettagrid_env_set.MettaGridEnvSet

num_agents: 24

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/multiagent/training/objects/terrain_from_numpy
  - /env/mettagrid/multiagent/training/objects/varied_terrain_all_sparse
  - /env/mettagrid/multiagent/training/objects/varied_terrain_balanced
  - /env/mettagrid/multiagent/training/objects/varied_terrain_maze
  - /env/mettagrid/multiagent/training/objects/varied_terrain_dense
  - /env/mettagrid/multiagent/training/objects/varied_terrain_all_sparse_small
  - /env/mettagrid/multiagent/training/objects/varied_terrain_balanced_small
  - /env/mettagrid/multiagent/training/objects/varied_terrain_dense_small
