defaults:
  - /env/mettagrid/multienv_mettagrid@
  - _self_

num_agents: 24

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/multiagent/training/objects/terrain_from_numpy_colors
  - /env/mettagrid/multiagent/training/objects/varied_terrain_all_sparse_colors
  - /env/mettagrid/multiagent/training/objects/varied_terrain_balanced_colors
  - /env/mettagrid/multiagent/training/objects/varied_terrain_maze_colors
  - /env/mettagrid/multiagent/training/objects/varied_terrain_dense_colors
  - /env/mettagrid/multiagent/training/objects/varied_terrain_all_sparse_colors_small
  - /env/mettagrid/multiagent/training/objects/varied_terrain_balanced_colors_small
  - /env/mettagrid/multiagent/training/objects/varied_terrain_maze_colors_small
  - /env/mettagrid/multiagent/training/objects/varied_terrain_dense_colors_small
