defaults:
  - /env/mettagrid/multienv_mettagrid@
  - _self_

num_agents: 24

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/multiagent/training/objects/terrain_from_numpy
  - /env/mettagrid/multiagent/training/objects/varied_terrain_all_sparse
  - /env/mettagrid/multiagent/training/objects/varied_terrain_balanced
  - /env/mettagrid/multiagent/training/objects/varied_terrain_maze
  - /env/mettagrid/multiagent/training/objects/varied_terrain_sparse_altars_dense_objects
