defaults:
  - /env/mettagrid/mettagrid@
  - _self_

num_agents: 24
sampling: 1
game:
  num_agents: 24  #how many agents are in the map x2
  agent:
    max_inventory: 10
  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.terrain_from_numpy_objects.TerrainFromNumpy
      border_width: 1
      dir: "terrain_maps_nohearts"
      num_agents: ${div:${....num_agents},4}
      teams: ["team_1", "team_2", "team_3"]
      object_colors: ["red", "green", "blue"]

  objects:
    altar:
      hp: 30
      input_battery: 3
      output_heart: 1
      max_output: 10
      conversion_ticks: 1
      cooldown: ${sampling:1, 20, 10}
      initial_items: 1

    mine.red:
      hp: 30
      output_ore.red: ${choose:0,1,1,2}
      color: 0
      max_output: 10
      conversion_ticks: 1
      cooldown: ${sampling:0, 100, 50}
      initial_items: 1

    mine.blue:
      hp: 30
      color: 1
      output_ore.blue: ${choose:0,1,1,2}
      max_output: 10
      conversion_ticks: 1
      cooldown: ${sampling:0, 100, 50}
      initial_items: 1

    mine.green:
      hp: 30
      output_ore.green: ${choose:0,1,1,2}
      color: 2
      max_output: 10
      conversion_ticks: 1
      cooldown: ${sampling:0, 100, 50}
      initial_items: 1


    generator.red:
      hp: 30
      input_ore.red: 1
      output_battery: ${choose:0,1,1,2}
      color: 0
      max_output: 10
      conversion_ticks: 1
      cooldown: ${sampling:0, 50, 25}
      initial_items: 1

    generator.blue:
      hp: 30
      input_ore.blue: 1
      output_battery: ${choose:0,1,1,2}
      color: 1
      max_output: 10
      conversion_ticks: 1
      cooldown: ${sampling:0, 50, 25}
      initial_items: 1

    generator.green:
      hp: 30
      input_ore.green: 1
      output_battery: ${choose:0,1,1,2}
      color: 2
      max_output: 10
      conversion_ticks: 1
      cooldown: ${sampling:0, 50, 25}
      initial_items: 1
