defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1
num_agents: 24

game:
  num_agents: 24
  max_steps: 25
  agent:
    max_inventory: 10

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    border_width: 6
    num_rooms: 4

    room:
      _target_: mettagrid.config.room.navigation.varied_terrain_objects.VariedTerrainObjects
      width: ${sampling:20,50,30}
      height: ${sampling:20,50,30}
      border_width: ${sampling:1,6,3}
      num_agents: ${div:${....num_agents},4}
      style: sparse-altars-dense-objects # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
      teams: ["team_1", "team_2", "team_3"]
      objects:
        altar: ${sampling:1,10,2}
        mine.red: ${sampling:2,10,2}
        generator.red: ${sampling:2,10,2}
  objects:
    altar:
      hp: 30
      input_battery: 3
      output_heart: 1
      max_output: 10
      conversion_ticks: 1
      cooldown: 1
      initial_items: 0

    mine.red:
      hp: 30
      output_ore.red: 1
      color: 0
      max_output: 10
      conversion_ticks: 1
      cooldown: 1
      initial_items: 1

    generator.red:
      hp: 30
      input_ore.red: 1
      output_battery: 1
      color: 0
      max_output: 10
      conversion_ticks: 1
      cooldown: ${sampling:0, 5, 25}
      initial_items: 1
