defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 24

  agent:
    max_inventory: 5
  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.config.room.navigation.varied_terrain_objects.VariedTerrainObjects
        width: ${sampling:50,100,60}
        height: ${sampling:50,100,60}
        border_width: ${sampling:1,6,3}
        agents: 6
        style: maze # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
      - _target_: mettagrid.config.room.navigation.varied_terrain_objects.VariedTerrainObjects
        width: ${sampling:50,100,60}
        height: ${sampling:50,100,60}
        border_width: ${sampling:1,6,3}
        agents: 6
        style: maze # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
      - _target_: mettagrid.config.room.navigation.varied_terrain_objects.VariedTerrainObjects
        width: ${sampling:50,100,60}
        height: ${sampling:50,100,60}
        border_width: ${sampling:1,6,3}
        agents: 6
        style: maze # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
      - _target_: mettagrid.config.room.navigation.varied_terrain_objects.VariedTerrainObjects
        width: ${sampling:50,100,60}
        height: ${sampling:50,100,60}
        border_width: ${sampling:1,6,3}
        agents: 6
        style: maze # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}
