# Config: choose any style, including the new "cylinder_world"
defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 48

  agent:
    max_inventory: 5
  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    border_width: 6

    rooms:
      - _target_: mettagrid.config.room.navigation.cylinder_world.CylinderWorld
        width: 60
        height: 60
        border_width: 1
        agents: 12
        team: team_1
      - _target_: mettagrid.config.room.navigation.cylinder_world.CylinderWorld
        width: 60
        height: 60
        border_width: 1
        agents: 12
        team: team_2
      - _target_: mettagrid.config.room.navigation.cylinder_world.CylinderWorld
        width: 60
        height: 60
        border_width: 1
        agents: 12
        team: team_3
      - _target_: mettagrid.config.room.navigation.cylinder_world.CylinderWorld
        width: 60
        height: 60
        border_width: 1
        agents: 12
        team: team_4

  reward_sharing:
    groups:
      team_1:
        team_1: 0.6
      team_2:
        team_2: 0.6
      team_3:
        team_3: 0.6
      team_4:
        team_4: 0.6
