defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 4
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.room.navigation.cylinder_world_sequence.CylinderWorldSequence
      width: ${sampling:75,120,60}
      height: ${sampling:75,120,60}
      border_width: ${sampling:1,6,3}
      agents: 1
      objects:
        altar: ${sampling:15,25,20}
        mine: ${sampling:15,25,20}
        generator: ${sampling:15,25,20}
  objects:
    altar:
      cooldown: 255
      input_battery: 1
      output_heart: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
    mine:
      cooldown: 255
      output_ore: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 1
    generator:
      cooldown: 255
      input_ore: 1
      output_battery: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
