defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 4
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.room.navigation.mem_varied_terrain.MemVariedTerrain
      width: ${sampling:20,60,25}
      height: ${sampling:20,60,25}
      border_width: ${sampling:1,6,3}
      agents: 1
      style: all-sparse
      objects:
        altar: ${sampling:1,3,3}
        mine.red: ${sampling:1,3,3}
        generator.red: ${sampling:1,3,3}
  objects:
    altar:
      cooldown: 5
      input_battery: 1
      output_heart: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
    mine.red:
      cooldown: 5
      output_ore.red: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 1
    generator.red:
      cooldown: 5
      input_ore.red: 1
      output_battery: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
