_target_: metta.env.mettagrid_env_set.MettaGridEnvSet

num_agents: 4
sampling: 1

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/navigation_sequence/training/varied_terrain_sparse_sequence
  - /env/mettagrid/navigation_sequence/training/varied_terrain_balanced_sequence
  - /env/mettagrid/navigation_sequence/training/varied_terrain_dense_sequence
  - /env/mettagrid/navigation_sequence/training/varied_terrain_maze_sequence
  - /env/mettagrid/navigation_sequence/training/mem_sparse_sequence
  - /env/mettagrid/navigation_sequence/training/mem_balanced_sequence
  - /env/mettagrid/navigation_sequence/training/mem_dense_sequence
  - /env/mettagrid/navigation_sequence/training/mem_maze_sequence