defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
  num_agents: 1
  max_steps: 300
  agent:
    rewards:
      heart: 1
  map_builder:
    _target_: mettagrid.room.mean_distance.MeanDistance
    width: 11
    height: 11
    mean_distance: 6
    border_width: 3
    agents: 1
    objects:
      mine.red: 1
      # mine.blue: 1
      # mine.green: 1
      altar: 1
      generator.red: 1

  objects:
    altar:
      cooldown: 1
      input_battery: 1
      output_heart: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
    mine.red:
      cooldown: 255
      output_ore.red: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
    generator.red:
      cooldown: 1
      input_ore.red: 1
      output_battery: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0