defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 4
  map_builder:
    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.room.navigation.varied_terrain_sequence.VariedTerrainSequence
      width: ${sampling:75,120,60}
      height: ${sampling:75,120,60}
      border_width: ${sampling:1,6,3}
      agents: 1
      style: all-sparse
      objects:
        altar: ${sampling:30,75,50}
        mine: ${sampling:30,75,50}
        generator: ${sampling:30,75,50}
  objects:
    altar:
      cooldown: 255
      input_battery: 1
      output_heart: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
    mine.red:
      cooldown: 255
      output_ore.red: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 1
    generator.red:
      cooldown: 255
      input_ore.red: 1
      output_battery: 1
      max_output: 1
      conversion_ticks: 1
      initial_items: 0
